### ISSUE TITLE
Private Window: Zoom percentage indicator on the address bar has a black font instead of white.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#102]
1- Open a page in a Private Window
2- Zoom in.

**Result:** The zoom percentage icon on the address bar has a black font instead of white.

Sorry if this is not possible to fix or have been brought before.

**Comment by Zonnev** [comment]
I fixed this recently, I checked once again but can not replicate this issue, it stays white on my side. I presume you talking about the zoom function add on from Firefox, right?

**Comment by Blast-City** [comment]
> I fixed this recently, I checked once again but can not replicate this issue, it stays white on my side. I presume you talking about the zoom function add on from Firefox, right?

Thanks for the prompt reply.

I'm talking about the elipse icon that only appears on the address bar when the zoom is different than 100%. It's not an add-on or the icon that can be added through the customize menu.

I checked my UserChrome and I'm running the latest version.

**Comment by Zonnev** [comment]
Ahh, thanks to people like you I discover new things not being fixed yet :) It's fixed now in the new userChrome's.

**Comment by Blast-City** [comment]
You're doing a great work. It's crazy how fast you fix this unimportant issues.
