### ISSUE TITLE
Steam: Age restriction warning doesn't show days or year until mouse hover.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#104]
1- Go to the Cyberpunk 2077 Steam page.
2- Use the drop down menus to input your age.

**Result:** The day or year numbers only show when an user hover with the mouse. This doesn't happen on the default Firefox.

**Comment by Zonnev** [comment]
Hi, I managed to fix this :) You can install the new userChrome's.
