### ISSUE TITLE
Clicking on a tab immediately chooses one of the search suggestions if the address bar is already expanded.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#105]
1- Search for something on the address bar.
2- Press Ctrl+t to open a new tab.
3- Return to the tab on 1.

Result: The search suggestion that is beneath the mouse cursor gets automaticity selected when the mouse button is released.

This is happening because, unlike default Firefox, the Tab bar is beneath the address bar which creates this problem. Is this something that can be solved through the css file or it's only fixable by Mozilla?

**Comment by Zonnev** [comment]
You are right, such a function is not fixable with CSS. It's unfortunate in my theme that the active tab is under the megabar in this situation...

**Comment by Blast-City** [comment]
Do you know how Epiphany handles this situation?

**Comment by Zonnev** [comment]
Epiphany doesn't have a extending url bar.

**Comment by Blast-City** [comment]
Doesn't it suggest history items when you start to type in the address bar?

**Comment by Zonnev** [comment]
Yes it does, and this extension of the url bar goes back into it's original 'small' state when you select another (first) tab. I think Firefox isn't programmed to do this since it has their tabs above the url bar, originally.

**Comment by Blast-City** [comment]
Thanks.
That was what I wanted to know. How do you bring back the suggestions when you select the tab again? Press the Down arrow?

**Comment by Zonnev** [comment]
In Firefox, to bring back the suggestions you have to click on the url bar again. When you start typing something, the text stays in the url bar on that tab, you can click the url bar and it will show the suggestions.

**Comment by Zonnev** [comment]
A strange thing Firefox does, is that it saved the text you typed also in the first tab. I don't know why this is happening, but I think it's not solvable with CSS...

**Comment by Blast-City** [comment]
I will try to ask around if there is a way to disable address bar expansion on tab switch. If there isn't, I will try to file an issue on Bugzilla.
Thanks.
