### ISSUE TITLE
Extend 'Conceal' Font Compatibility

### ISSUE THREAD

**Issue by Cjnator38** [Zonnev/elementaryos-firefox-theme#106]
Currently, when taking a screenshot from the elementary Screenshot app with the "Conceal Text" option enabled, not everything is replaced with the font. This might be a Firefox issue that might be unfixable, but there might be a way to handle text the same way the Address Bar does, just without the ability to select the text.
![image](https://user-images.githubusercontent.com/39870226/103734141-ed5c0000-4fb0-11eb-8c4b-56c24599a614.png)

**Comment by Zonnev** [comment]
I fixed this, now the tabs etc. are all acting the same in Screenshot with conceal text option on. You can install the new userChrome's.
