### ISSUE TITLE
Bookmarks Toolbar size increases if an icon is placed on it.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#107]
1- Enable the Bookmarks Toolbar.
2- Using the Customize Menu try to add any icon to the Bookmarks toolbar.

Unlike the default Firefox theme, adding any icon to the Bookmarks Toolbar makes it size increase.

Thanks.

**Comment by Zonnev** [comment]
You can adjust `#PersonalToolbar` padding to 2px maybe if you want to narrow the bookmarks bar. It's around line 1151 in the userChrome.

**Comment by Blast-City** [comment]
Thanks.

The problem seems to be the "Import Bookmarks" icon. Removing it from the Bookmarks Toolbar returns the bar to a normal size.

I've tried other icons on the Bookmarks bar and it doesn't seem to change the bar size. Only the "Import Bookmarks" icon changes it.

Is this something that could be fixed?

**Comment by Zonnev** [comment]
Ah yes, I understand the problem now. It can be fixed if you put `display: none !important` to the selector `#import-button` for both `label` and `image`. So it would look something like this:

```
#import-button label image {
display: none !important;
}
```

**Comment by Blast-City** [comment]
> Ah yes, I understand the problem now. It can be fixed if you put `display: none !important` to the selector `#import-button` for both `label` and `image`. So it would look something like this:
> 
> ```
> #import-button label image {
> display: none !important;
> }
> ```

Hi.

I changed the title and edited the issue since it seems that every icon is affected by this issue. Please tell me if this is something that it can be fixed by you or if I should close this issue.

Thanks and sorry for the trouble.

**Comment by Zonnev** [comment]
I will try to fix this later.

**Comment by Zonnev** [comment]
I finally fixed the height of the bookmarks bar. Sorry for waiting!

**Comment by Blast-City** [comment]
Hi.

I just tested and it seems to be better, but I think it still have some extra padding. If I add the same icons to the Tab Bar I don't see that size difference.

Thanks.

**Comment by Zonnev** [comment]
I now have fixed the "jumping" height of the bookmarks bar. It's now the same height when adding bookmarks and removing all. You can download the latest userChrome to check it out.

**Comment by Blast-City** [comment]
I tested it and it seems to be working fine.

The bookmarks toolbar height still seems a little bit big for me. Don't you think that it would look better if the bookmarks toolbar had the same height as the Tabs Toolbar?

**Comment by Zonnev** [comment]
Hi, I've made the bookmarks bar the same height as the tabs toolbar as you requested. You can install the latest userChrome to check it out.

**Comment by Zonnev** [comment]
Again an update: bookmarks bar in customization palette was messy so I fixed that in the newest userChrome.

**Comment by Blast-City** [comment]
It looks great.

I haven't found any issues.

Thank you for all the work.

**Comment by Blast-City** [comment]
Just a question: Is there a reason why the Menu Bar (File, Edit, View, etc...) has a 29px height while the Tab Bar has a 30px height?

**Comment by Zonnev** [comment]
The menu bar **items** are 29px height. That makes the menu bar itself 30px of height, only this value is not set in my userChrome but it is 30px of height (same height as tab bar).

**Comment by Blast-City** [comment]
Oh Ok. Thanks.

**Comment by Zonnev** [comment]
I fixed an issue I had with the bookmarks import button icon going large when closing and opening the bookmarks bar. This is solved in the new userChrome.
