### ISSUE TITLE
Is Tor-browser supported?

### ISSUE THREAD

**Issue by Zbergen-cli** [Zonnev/elementaryos-firefox-theme#108]
Hello!

Is Tor-browser supported, which in turn is built on Firefox-esr? Latest version 10.0.13 (based on Mozilla Firefox 78.8.0esr)

**Comment by Zonnev** [comment]
Sorry, I don't know if the Tor-browser would be fully themed, I don't have it installed. I guess some elements would be themed but not sure if it puts the tabs under the navigation bar.

**Comment by Zbergen-cli** [comment]
The good news is that the theme works.
The bad news is that the style does not apply to some elements. For example, in the right-click menu, the rounding works fine only on a light background. When hovering over any of the menu items, it starts bouncing and changing size slightly.

Oddly, even manually assigning styles has no effect on these elements. How to work with them in this case?

**Comment by Zonnev** [comment]
Maybe it's better to remove all styling for the right-click menu's in the Tor-browser's userChrome. You can remove everything between line 9 and 643 and see how things are then. Good luck.
