### ISSUE TITLE
"What's New" Icon is black on Private Windows.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#109]
The "What's New" icon remains black when an user opens a Private Window.

**Comment by Zonnev** [comment]
Yes, I know this problem, I just don't know how to enable this icon so I can inspect it with the Browser Tool...

**Comment by Blast-City** [comment]
Closing this issue.

If anyone find how to fix this, please feel free to comment and I will open it again. Thanks.
