### ISSUE TITLE
The "show more" button on bookmark bar seems to have more padding

### ISSUE THREAD

**Issue by hiunnhue** [Zonnev/elementaryos-firefox-theme#11]
please see the attched screenshot: 

![image](https://user-images.githubusercontent.com/1015601/52899748-75ec1e80-3228-11e9-905d-6fc832133d5a.png)

**Comment by Zonnev** [comment]
In my theme this button is not styled, so its default behaviour. The upper button in the header bar has the same id as the lower one in the bookmarks bar, yet Firefox displays them differently.
