### ISSUE TITLE
Rounded corners dark theme issue. Please, reply...

### ISSUE THREAD

**Issue by Zonnev** [Zonnev/elementaryos-firefox-theme#111]
Now in Firefox 88 the suppose to be 'rounded corners' for the dark theme are square again! I don't know what to do anymore, it seems for elementary OS they don't care about this issue. 

I'm actually thinking to regress my Firefox theme as well by only supporting the default theme (light) and the private mode but not the dark theme anymore... 

What do you think? Thanks for your replies.

**Comment by decisoft** [comment]
Hi! I'm using your theme. I don't care about dark theme, and I think I won't use dark mode on eOS 6. But the dark mode on eOS 6 is a feature that has been requested to integrate natively. So maybe much more users than me will find quite nice to use your theme on dark mode. But it's up to you! I'll continue using this amazing theme.
Thanks for your work!

**Comment by Zonnev** [comment]
I have tested things and when dark mode is enabled in Tweaks for eOS 6.0 the corners are rounded. I'm glad this is the case so people can still enjoy a complete dark theme.
