### ISSUE TITLE
Not working in Firefox flatpak

### ISSUE THREAD

**Issue by Suzie97** [Zonnev/elementaryos-firefox-theme#112]
![Screenshot from 2021-05-02 00-06-51](https://user-images.githubusercontent.com/68198116/116791814-66401400-aada-11eb-9210-d43f04c78622.png)

When firefox is restarted, it doesn't work.

**Comment by Zonnev** [comment]
Maybe you forgot to enable the legacy profile customizations toolkit in about:config? See the readme file for instructions.

**Comment by Suzie97** [comment]
Oh yeah! Your right. My bad.
