### ISSUE TITLE
Proton context menus

### ISSUE THREAD

**Issue by decisoft** [Zonnev/elementaryos-firefox-theme#113]
Hi!

I'm wondering if, when Firefox 89 with the new UI Proton arrives, you'll be able to merge all the Proton stuff to your theme, at least the branch of Odin. I've seen that the floating tabs are already on the theme.

Thanks in advance and good job!

**Comment by Zonnev** [comment]
I have tested my theme in eOS 6 with Firefox Nightly and the only thing I encountered was the tabs not aligning very well. I adjusted this issue in the latest userChrome. I think that did cover all the changes going to the Proton UI, so yes, my theme does support Proton.

**Comment by decisoft** [comment]
Thanks!
