### ISSUE TITLE
Zoom indicator icon on the address bar is cut on the bottom.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#114]
1- Click on an empty space of a webpage to disable the expanded address bar.
2- Zoom-in or Zoom-out.

Result: The bottom of the ellipsed shaped icon that indicates the zoom is cut on the bottom.

Note: I don't remember this happening so it mus be a recent regression.

**Comment by Zonnev** [comment]
Thanks again! It's fixed in the new userChrome.
