### ISSUE TITLE
Tabs are weird after newest firefox update (v89.0)

### ISSUE THREAD

**Issue by rasmus91** [Zonnev/elementaryos-firefox-theme#117]
After upgrading firefox to latest version i have problems with the Tabs looking weird.

![Skærmbillede fra 2021-06-04 10-42-43](https://user-images.githubusercontent.com/2297739/120773427-9e93a180-c521-11eb-9430-2ae488d76459.png)
(see middle tab)

**Comment by Zonnev** [comment]
You have not installed the newest userChrome. I know this because you still have the blue line above the active tab which I have removed some versions ago.

**Comment by rasmus91** [comment]
Weeeeeell...

That did not exactly improve things. I don't know what the heck is up here, but somethings going on. (this is after installing the newest version and restarting FF)

![Skærmbillede fra 2021-06-04 22-19-10](https://user-images.githubusercontent.com/2297739/120858399-06c69f80-c583-11eb-97b7-01a0d2cfcbff.png)

**Comment by JayXT** [comment]
In my case, after updating Firefox and userChrome.css to the latest version the tabs look disproportionately large.
![Screenshot from 2021-06-05 09-04-27](https://user-images.githubusercontent.com/8045344/120881919-2b4f6580-c5dd-11eb-9a5f-9f1d6164b315.png)

**Comment by Zonnev** [comment]
Sorry!!! I forgot to end the new CSS code with }, so the following tab code wasn't applied anymore... The new userChrome for the default layout is fixed.

**Comment by JayXT** [comment]
Wow... That was incredibly fast fix. Thank you!
I'm not sure if it was intended, but tab titles aren't centered. 
![Screenshot from 2021-06-05 11-11-02](https://user-images.githubusercontent.com/8045344/120884956-eb917980-c5ee-11eb-8098-9f953a09ded9.png)

**Comment by Zonnev** [comment]
Hi @JayXT, I have tried to center the tab labels but I can not figure out why it's not working. Proton layout does make them align to the left by default but I don't know which part of the code does this. I will keep working on it since it has been bothering me from the beginning of the Proton versions...

**Comment by Zonnev** [comment]
@JayXT and @Blast-City I decided to keep the left text alignment because it looks okay with the secondary tab label when playing video's or audio files online. If they were in centered it wouldn't look so well, I think. Hope you can live with that!

**Comment by rasmus91** [comment]
And it seems to work perfectly again. Thank you <3

![Skærmbillede fra 2021-06-07 09-33-22](https://user-images.githubusercontent.com/2297739/120977282-74392280-c773-11eb-8a4e-76f3d70389ae.png)

**Comment by Blast-City** [comment]
@zonnev, I'm posting a question here to not open a new issue:

The space between the close button and the tab name (left side) seems to be bigger than the space between the text and the favicon (right side) which makes it seem that the text is "right aligned" on longer tab names. On some tab names you can even see the text beneath the favicon. Is this a bug or a design choice?

**Comment by Zonnev** [comment]
@Blast-City I moved the favicon so you can see the fade out of the tab text now. It was something I didn't notice so it wasn't a bug or design choice but a settting in Proton that I needed to translate to my theme because in my theme the tab elements are reversed and the margin was then on the wrong side of the favicon. Thanks for noticing this issue! It's fixed in the new userChrome.

**Comment by Zonnev** [comment]
@Blast-City I had to do another fix because the favicon was jumping to the left when muting the tab and also the fade out of the text was gone after muting the tab. It's all fixed now in the new userChrome.

**Comment by Blast-City** [comment]
Thanks. The fade now ends before the favicon.

I think that text is still too close to the favicon compared to the close button. It looks like this to me:

|x|   |long_text_here| |f|

Instead of:

|x| |long_text_here| |f|

**Comment by Zonnev** [comment]
@Blast-City You are right, I fixed this in the new userChrome. Thanks for explaining the issue clearly.

**Comment by Blast-City** [comment]
It looks great.

Thank you very much.
