### ISSUE TITLE
[Proton] Playback tab indicator is cut on the bottom.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#118]
1- Go to Youtube and play a video.

Result: The "Playback" text on the bottom of the tab is cut.

**Comment by Zonnev** [comment]
Hi I've done some things to the tab layout:
![Schermafdruk van 2021-06-04 17 37 55](https://user-images.githubusercontent.com/32688765/120829981-534bb400-c55e-11eb-910b-85f6f42f221d.png)
I think this is better, or do you see other things happening there?

**Comment by Blast-City** [comment]
Hi.

The theme stopped working on my computer. There is no elementary icons, the tabs look like default. The only thing that it changed was tab bar and the address bar position. I've tried the previous version and it's working, so it must something that was introduced on the latest version.

Is it working on your computer?

Thanks.

**Comment by Zonnev** [comment]
Sorry I forgot to end the new CSS code with }, so the following tab code wasn't applied anymore... The new userChrome for the default layout is fixed.
