### ISSUE TITLE
Reposition the tab close button on the right side for "Close Only Right" and "Windows" Layout

### ISSUE THREAD

**Issue by hrstwn** [Zonnev/elementaryos-firefox-theme#120]
Can we have the close button on the tab on the right side following the layouts that have the close button window on the right side too like in GNOME and Windows?

Because I really like this theme and I also use it in GNOME.
Thanks.

**Comment by Blast-City** [comment]
Hi.

Have you tried this one? https://github.com/rafaelmardojai/firefox-gnome-theme

**Comment by hrstwn** [comment]
I have actually but not quite like how the tabs behave. I prefer this theme because I really like the look. Don't mind the inconsistency since it's rather unnoticeable with Adwaita.

For people who choose the close button on the right layout I think it'd help them since the option for it is provided in the installation. But it's definitely a minor request, not an issue.

**Comment by Blast-City** [comment]
Oh OK.

Since other elementary apps have the tabs close button on the left no matter what the window buttons layout is, I think this a change that should be tweaked by the user itself after installing the theme.

I'm sure that the author will help you.

**Comment by Zonnev** [comment]
Yes @Blast-City is right about this. 

@hrstwn you can reverse the layout of all tabs by deleting  `-moz-box-direction: reverse !important;` on line 987, 992 and 1040 or change the value to `-moz-box-direction: normal !important;`.

**Comment by hrstwn** [comment]
Oh okay cool. Thanks!
