### ISSUE TITLE
[Proton] Search page options don't show a check mark when activated.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#121]
1- Go to a webpage.
2- Press Ctrl+f to search a word in the current page.

**Result:** The "Highlight All", "Match Case", etc... boxes don't have a check mark when activated. The Private Mode shows a check box, but the background is purple which I'm not sure if it is another issue.

**Comment by Zonnev** [comment]
I have fixed this, all check boxes are visible now :)

**Comment by Blast-City** [comment]
Hi.

Sorry for bothering you, but now they're inverted.

Normal windows:
Selected - White filled square with blue outline.
Unselected - Blue filled square with checkmark.

Private windows:
Selected - Purple filled squares with checkmark.
Unselected - Blue filled squares with checkmark.

**Comment by Zonnev** [comment]
> Hi.
> 
> Sorry for bothering you again, but now they're inverted.
> 
> Normal windows:
> Selected - White filled square with blue outline.
> Unselected - Blue filled square with checkmark.
> 
> Private windows:
> Selected - Purple filled squares with checkmark.
> Unselected - Blue filled squares with checkmark.
> 
> Thanks.
> 

Wow, some things went not very well today... 
Well... this is solved again in the new userChrome!

**Comment by Blast-City** [comment]
Thanks. It seems to be fixed.

Just a question: Is it normal for the unselected squares to be purple when the background is light grey? I get it when the background is purple, but when the background is light grey it looks kind of out of place. Is it possible to change the search bar just for the private window or is this "component" shared with normal windows?

**Comment by Zonnev** [comment]
> Just a question: Is it normal for the unselected squares to be purple when the background is light grey? I get it when the background is purple, but when the background is light grey it looks kind of out of place. Is it possible to change the search bar just for the private window or is this "component" shared with normal windows?

I have made the unchecked checkbox white for private mode in the new userChrome.
