### ISSUE TITLE
White text on suggestions

### ISSUE THREAD

**Issue by Hedronmx** [Zonnev/elementaryos-firefox-theme#122]
![img](https://i.imgur.com/uLuzop7.png)

Not sure if this because of the theme or something else.

**Comment by Zonnev** [comment]
It's in the Alpenglow theme. You have to use the default system theme or dark theme, Alpenglow theme is not supported, sorry.

**Comment by Hedronmx** [comment]
Oh snap! I changed the theme on windows, I guess it synced to my linux pc. thanks. My bad
