### ISSUE TITLE
Strange frame on the active tab

### ISSUE THREAD

**Issue by Zbergen-cli** [Zonnev/elementaryos-firefox-theme#123]
After right-clicking on the active tab, a strange frame appears. Take a look:
![Ekrankopita je 2021-06-06 13 32 31](https://user-images.githubusercontent.com/72291366/120915059-3663cd80-c691-11eb-879c-1db0a5ae4ef5.png)
I don't know if this is caused by the recent firefox update. Can we hide it with a css?

**Comment by Zonnev** [comment]
Hm, I can not reproduce this issue. Right-clicking the active tab should result in opening the menu for it. Maybe you need to install the newest userChrome?

**Comment by Zbergen-cli** [comment]
The menu is called, but was hidden for the screenshot. I updated earlier today, but just in case, I installed the latest version. Unfortunately the frame still appears. Firefox 89.0

**Comment by Zonnev** [comment]
You have turned on accessibility feature in Firefox but in Proton versions I don't know where that feature is located. You can go to `about:config` and search `browser.display.focus_ring_width` and set it to `0`. Maybe that helps.

Source: https://support.mozilla.org/en-US/questions/990092

**Comment by Blast-City** [comment]
Hi.

Is it a new profile? I remember that **setting ui.context_menus.after_mouseup** in about:config would cause this issue when it was enabled.

**Comment by Zbergen-cli** [comment]
@Blast-City Great! Thank you!

**Comment by Zbergen-cli** [comment]
This problem can also be solved by
```
.tab-content:not([pinned]) {
    outline: 0px dotted !important;
}
```
