### ISSUE TITLE
Address bar "Allow Notifications" icon is small.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#125]
The "Allow Notifications" icon on the address bar is small. This only happens when the address bar is not expanded.

**Comment by Zonnev** [comment]
Hello, I have made all icons that are under the notification popup box bigger. I think this includes the DRM icon too, you have to check that yourself after you installed the new userChrome.

**Comment by Blast-City** [comment]
Hi.

This issue seems to be back.

Thanks.

**Comment by Zonnev** [comment]
Maybe they've changed how they handle these icons. I've set all images under notification popup box the same values now so the sizing should be alright for all these icon's now. Check the new userChrome.

**Comment by Blast-City** [comment]
Fixed.

Thank you very much.
