### ISSUE TITLE
Customize Toolbar Menu: Home Icon is small compared to the other available icons.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#127]
1- Right Click on any part of the toolbar and click on "Customize Toolbar..."
2- Check the available icons.

The Home icon is small compared to the other icons available on the Customize Toolbar Menu. Once you had the Home icon to the toolbar it becomes the normal size, but while it is not added it remains small compared to the other icons. This doesn't happen on the default Firefox theme.

**Comment by Zonnev** [comment]
Thanks! I have fixed the small icons for the Home button and Reload button in the Customization palette.
