### ISSUE TITLE
Customize Toolbar Menu: Moving the mouse over the Overflow Menu icon makes the highlight disappear.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#128]
1- Right Click on any part of the toolbar and click on "Customize Toolbar..."
2- Move the mouse over the Overflow Menu icon.

The highlight disappears once you move the mouse over the Overflow Menu icon. This doesn't seem to happen on the the default Firefox theme.

**Comment by Zonnev** [comment]
I'm sorry, this I can not change since my theme wants to not show the highlighting of these buttons and therefore you see the opposite effect in the customization mode. I will maybe look at this issue another time. Thanks anyway!

**Comment by Zonnev** [comment]
I fixed this issue in the new userChrome you can install now.

**Comment by Zonnev** [comment]
It's not fixed yet because outside the customization mode the overflow button shows the hover effect, this is not wanted. I will work on it.

**Comment by Zonnev** [comment]
It's fixed now!
