### ISSUE TITLE
Switches on the Address Bar "Shield" Menu are black instead of blue.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#130]
1- Go to a website where Firefox blocks content (address bar shield icon turns blue).
2- Click on shield icon in the address bar

The switches should be blue like the ones in the new tab personalize menu.

**Comment by Zonnev** [comment]
I've deleted a lot of ccs involving the protections menu. All the switches are blue now, thanks!
