### ISSUE TITLE
Private Window. Selected Search Engine indicator text and x button is black.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#134]
1- Open a private window.
2- Click on the address bar and then select any of the available search engines on the bottom.

Result: The selected search engine indicator text and x button is black which results in a low contrast against the purple background of the address bar.

**Comment by Zonnev** [comment]
As you can see, this is fixed :)

**Comment by Blast-City** [comment]
Nice!

Thanks.
