### ISSUE TITLE
It doesn't show window controls on any layout in Firefox 90

### ISSUE THREAD

**Issue by Sranzx** [Zonnev/elementaryos-firefox-theme#135]
There is the space for the window control buttons but it's just empty.

**Comment by Zonnev** [comment]
The window button layouts work together with [elementary Tweaks](https://github.com/elementary-tweaks/elementary-tweaks). Have you installed that software?

**Comment by Sranzx** [comment]
> The window button layouts work together with [elementary Tweaks](https://github.com/elementary-tweaks/elementary-tweaks). Have you installed that software?

Yes, I did.

**Comment by Zonnev** [comment]
So the thing is that you set Tweaks the same as the window button layout you choose to install. So after installing option 5 (Minimize right) you need set Tweaks to window button layout "Minimize Right". Hope that will solve the problem.
