### ISSUE TITLE
Odin theme is the main branch now!

### ISSUE THREAD

**Issue by Zonnev** [Zonnev/elementaryos-firefox-theme#136]
Hello users!

The Odin theme is the main branch now Odin (elementary OS 6.0) has been released.
Soon I will delete the Hera (elementary OS 5.0) theme but you can still find it here: https://github.com/Zonnev/elementaryos5-firefox-theme, which stays updated. 

You can post issues for the elementary OS Hera theme here: https://github.com/Zonnev/elementaryos5-firefox-theme/issues

Thank you for using my theme!

**Comment by Hedronmx** [comment]
The best theme in the history of themes!!!

**Comment by Zonnev** [comment]
There is a new eOS version out called Jólnir. I need to rename the odin repository or else we might think this theme didn't update. I close this issue after the renaming is done.
