### ISSUE TITLE
Menu items are dancing

### ISSUE THREAD

**Issue by Zbergen-cli** [Zonnev/elementaryos-firefox-theme#137]
Hi. Items in the menu start dancing on hover:

https://user-images.githubusercontent.com/72291366/129000158-361e9f1b-50b0-4f35-9156-dbcc11f21ae8.mp4

I am using the latest userChrome.css

**Comment by Zonnev** [comment]
I think you are using the Odin theme on your elementary Hera install?

**Comment by Zbergen-cli** [comment]
Um, no elementary os 6, the theme is for firefox 90.0.2 Odin

**Comment by Zonnev** [comment]
Firefox just updated to 91, do you still have this problem on 91? I don't see this dancing on my Firefox. I installed Firefox by using `sudo apt install firefox`.

**Comment by ApmGor** [comment]
Verified. All menus dance when hovering the mouse cursor. Latest version of Firefox installed from `sudo apt install firefox`.

**Comment by Zbergen-cli** [comment]
Yes, version 91 has the same problem.

**Comment by Zonnev** [comment]
I think this issue is because of the text size option in Odin not set to standard. To solve this I have to stop painting shadows under the menus. You will see no shadow under the menus, shall I do this?

**Comment by Zonnev** [comment]
I have worked on this issue by removing lots of CSS involving the shadows under the menu's. The shadows are gone now and therefore the "dancing" menu items shouldn't appear anymore no matter which text size option you set in Odin desktop settings. 

I hope you all agree with this change and won't miss the shadows under the menu's. You can check the change out by installing the new userChrome of the Odin theme.
