### ISSUE TITLE
Second maximize button visible

### ISSUE THREAD

**Issue by StephanStanisic** [Zonnev/elementaryos-firefox-theme#139]
When firefox is in non maximized mode, and you maximize the window by dragging it onto the top of the screen, a second maximize button will be shown where it was before.

![image](https://user-images.githubusercontent.com/11994705/129393043-c6c70ea6-2c2c-4eb2-9756-1c2e73ff682c.png)

If you move focus to another window, and come back the second button will have disappeared. Not always though. Alt tab seems to work always.

I am running firefox as a flatpak, on the new eOS Odin.

**Comment by Zonnev** [comment]
Yes I noticed this too but the second buttons aren't clickable. In fact, when you hover the second buttons they will disappear like screen artifacts. I think this has something to do with userChrome and the legacy stylesheet plugin in Firefox not being fast enough. Firefox also has such screen artifacts with the right click menu's not vanishing quickly enough, leaving bits of the menu's on screen. I can't fix this I'm afraid...

Great to see the flatpak Firefox running my theme. It looks good :)

**Comment by Zonnev** [comment]
I find that hovering these buttons two times when maximizing Firefox two times (clicking the maximize button), the buttons stay away... Till you close the window and open Firefox again, the same routine seem to need to be done again. Let's hope some improvement will come in upcoming Firefox versions.

**Comment by Zonnev** [comment]
**Last possible solution to this problem:** put `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config` to false and close Firefox. Open Firefox again and put the toolkit to true. Close Firefox again, open it and you will notice this issue with the double window controls is gone.

**Comment by Zonnev** [comment]
Hmm, the issue comes back after restarting the computer... :(

**Comment by Zonnev** [comment]
Its fixed in the new userChrome. I thought it was unfixable but by simply removing display of the double window controls it was fixed.
