### ISSUE TITLE
Context menu barely readable - flatpak Firefox

### ISSUE THREAD

**Issue by levjad** [Zonnev/elementaryos-firefox-theme#142]
Using Firefox with dark theme + elementaryos-firefox-theme results in a bareley readable context menu. System is elementary OS 6 (odin).

![context_menu_barely_readable](https://user-images.githubusercontent.com/19470048/130981740-1c3e2fd0-d086-482e-a6f6-601b0138314a.png)

**Comment by Zonnev** [comment]
Your menu doesn't look like my menu at all, only the rounded corners are like my theme. I don't know what is "dark theme" in your sentence but I don't think you used Firefox's dark mode theme in the customization panel. I guess you try to use two theme's? My theme has a dark mode theme build in, you don't have to install any other theme to make Firefox dark.

**Comment by levjad** [comment]
Yes, I'm using the dark theme which is built into firefox. I updated the theme and now the context menu has the color of the light theme (built-in).

**Comment by Zonnev** [comment]
So, you are saying when Firefox is in dark mode, you get the context menu in light mode? Very strange... I don't have this issue on my PC so it's difficult for me to give you a solution for this issue...

**Comment by Zbergen-cli** [comment]
Couldn't reproduce it... Perhaps you are using a build based on an outdated firefox base...

![Ekrankopita je 2021-08-30 19 04 16](https://user-images.githubusercontent.com/72291366/131337260-e1fa6563-84e5-47b0-a4c6-8510885856dd.png)

I used the latest version of EOS, the latest version of firefox and the latest version of elementaryos-firefox-theme...

**Comment by kmandarin-orange** [comment]
I can confirm using the latest Firefox flatpak update I have this issue, running the latest version of this theme too. Tried using in combination with Pantheon Tweaks too and it seems like the context menu is pulling the background color from Firefox's built in dark theme, but taking shape/corner radius from the elementary theme.

![Screenshot from 2021-09-07 10-10-15](https://user-images.githubusercontent.com/55755379/132373976-39fb9628-7709-4287-b4b1-9ef6f44ed504.png)

**Comment by Zonnev** [comment]
Ok @kmandarin-orange thanks for showing the cause of the problem: flatpak version of Firefox. I removed the ability to install the userChrome in the Firefox flatpak directory. I recommend @levjad and @kmandarin-orange to install Firefox via the terminal, doing: `sudo apt install firefox` and remove the flatpak Firefox. Good luck!

**Comment by kmandarin-orange** [comment]
Okay, good to know that's the issue. I may end up switching my Firefox installation, but out of curiosity is it even possible to change that part of the theme for flatpaks?

**Comment by Zonnev** [comment]
> Okay, good to know that's the issue. I may end up switching my Firefox installation, but out of curiosity is it even possible to change that part of the theme for flatpaks?

I didn't look into it very well but it seems that flatpak has a difference naming some elements. I don't know why that is... The first thing I would do is delete the whole section about the right click menu's in the userChrome. It would work with the colours then, but it would not show the rounded corners. This can be solved, but the userChrome would be different than default. I won't maintain two userChrome's...

And I see there are a few more issues in flatpak, like the positions and the hover style of the window buttons and the pull down menu entries of the menu bar, they have a blue line and all the hovers are blue, too much work supporting another version of Firefox...

**Comment by kmandarin-orange** [comment]
Interesting, thanks for all that info. I might just remove the right click menu section in the userChrome then. Maybe someone familiar with flatpak could fork this project for flatpak-distributed Firefox installs. Thanks for the informative response!

**Comment by Zonnev** [comment]
> I might just remove the right click menu section in the userChrome then. 

You can remove line 9 to line 124.

**Comment by Zonnev** [comment]
I think this issue is solved, we know why the context menu's are not readable in the flatpak version of Firefox.
