### ISSUE TITLE
LibreWolf support

### ISSUE THREAD

**Issue by staniki** [Zonnev/elementaryos-firefox-theme#143]
Please add LibreWolf (https://librewolf-community.gitlab.io/) support auto-install in install.sh :)

**Comment by Zonnev** [comment]
I'm sorry, I can't support installations different than default Firefox, but how does my theme look on LibreWolf? Does it has the same problems as flatpak Firefox with issue #142?

**Comment by staniki** [comment]
i check this tomorrow and write here :)

**Comment by Zbergen-cli** [comment]
LW is supported, but you will probably have to make minor edits to userChrome.css yourself.

**Comment by Zonnev** [comment]
I installed LibreWolf from AppCenter and it has the same issues as the flatpak-distributed default Firefox, but this is because LibreWolf is also a flatpak distribution in the AppCenter. 

I can not support LibreWolf for the same reasons as in issue #142.

**Comment by Zonnev** [comment]
> LW is supported, but you will probably have to make minor edits to userChrome.css yourself.

User's shouldn't install LibreWolf from flatpak because this causes more issues. Best to try install LibreWolf with the [app image](https://gitlab.com/librewolf-community/browser/appimage/-/releases) I guess.

**Comment by staniki** [comment]
Ok guys, im install (paste in application (custom) folder) appimage LW, now what? How to install this theme in appimage? :)

**Comment by Zonnev** [comment]
@staniki go to https://librewolf-community.gitlab.io/install/ that page has a how to install an app-image section.

**Comment by Zonnev** [comment]
I have downloaded and made the AppImage executable and installed the userChrome in the `.librewolf/<profile>/` folder. All works fine so I close this issue with the notice that the installer of my theme is not supporting LibreWolf because users are more likely to install the flatpak version which causes problems.
