### ISSUE TITLE
Sometimes appear a second top-right button on the address bar

### ISSUE THREAD

**Issue by SteveFour** [Zonnev/elementaryos-firefox-theme#145]
## Step to reproduce:

1. Unmaximize the Firefox windows
2. Either change the window width or maximize the window.
3. If you click on it the window will be minimized
It is not a huge problem but it's just quite annoying.
Note: It immediately dissapear the moment you shake the window, press the alt button, or try to take a screenshot.

## Platform & Settings:

Elementary OS 6; Modzilla Firefox (not the Flatpak version).
Windows button layout: Chosen Default (custom) in my case: Replace maximize with minimize (change via dconf and Tweak). (though I don't think this is the problem)

**Comment by Zonnev** [comment]
Its fixed in the new userChrome. I thought it was unfixable but by simply removing display of the double window controls it was fixed.
