### ISSUE TITLE
Text not Visible in Page Info and Zoom Labels in Private Browsing Mode

### ISSUE THREAD

**Issue by candiedoperation** [Zonnev/elementaryos-firefox-theme#146]
@Zonnev, In Private Browsing mode, both the background color of the label and the foreground (text) color is white which makes it completely unreadable. I've Attached the below images for your reference.

|Normal Window|Private Browsing Mode|
|---|---|
| ![firefox-issue-normal](https://user-images.githubusercontent.com/47198395/133786054-0e30e15f-08a4-435f-b5c8-2ed0c388b852.png)| ![Firefox-Issue](https://user-images.githubusercontent.com/47198395/133785408-4ca7f635-c731-4ae8-b5e9-36334be0d42e.png)|

**The above Screenshot was taken on elementary OS Odin with the theme released on Sep 17, 2021**

**Comment by Zonnev** [comment]
I can not reproduce this issue. Could it be you are running flatpak version of Firefox, because I see this:
![Schermafdruk van 2021-09-19 15 55 54](https://user-images.githubusercontent.com/32688765/133930188-ed3be605-2c78-49cc-898f-827a8a7d1396.png) 
Uninstall Firefox from the AppCenter and make sure to install Firefox typing: `sudo apt install firefox` in the Terminal.

**Comment by candiedoperation** [comment]
> I can not reproduce this issue. Could it be you are running flatpak version of Firefox, because I see this:
> ![Schermafdruk van 2021-09-19 15 55 54](https://user-images.githubusercontent.com/32688765/133930188-ed3be605-2c78-49cc-898f-827a8a7d1396.png)
> Uninstall Firefox from the AppCenter and make sure to install Firefox typing: `sudo apt install firefox` in the Terminal.

No, it's not flatpak (BTW, I'm running firefox installed using `apt`). The issue happens only when firefox is in light theme. It works fine as shown in your screenshot only when dark theme is used in firefox

**Comment by Zonnev** [comment]
Sorry for misunderstanding. My theme works best with system theme in Firefox. Light theme is different in many ways, I have not adjusted my theme with light theme enabled. My theme support only dark and system theme modes.

**Comment by candiedoperation** [comment]
> Sorry for misunderstanding. My theme works best with system theme in Firefox. Light theme is different in many ways, I have not adjusted my theme with light theme enabled. My theme support only dark and system theme modes.

Okay, Thank You @Zonnev, I'll change Firefox to system theme and I'll be closing this issue then.
