### ISSUE TITLE
Headerbar bezel dragging

### ISSUE THREAD

**Issue by xchan14** [Zonnev/elementaryos-firefox-theme#148]
![Screenshot from 2021-10-05 21-40-35](https://user-images.githubusercontent.com/26490513/136036503-a29f6074-1c27-4311-b184-753a6814f057.png)
The upper bezel is not draggable.
The lower bezel is only draggable by lower half.

Suggestion:
Make search/url textbox draggable when on hold (keydown) just like the files app.

**Comment by Zonnev** [comment]
I've made the url bar "bezel" draggable, you can install the new userChrome. Thanks :)

**Comment by xchan14** [comment]
That is cool. Thanks.
