### ISSUE TITLE
[feature request] Thunderbird theme

### ISSUE THREAD

**Issue by dre1080** [Zonnev/elementaryos-firefox-theme#149]
Is it possible to make elementary OS Odin thunderbird theme? Similar to #57 but updated for Odin

**Comment by Zonnev** [comment]
Hi, I've edited the userChrome from #57 to match Odin's tabs. This userChrome for Thunderbird only themes the tabs and tab bar and changes the main menu icon with the elementary wheel. Use this userchrome _without_ disabling the title bar.

You can download the userChrome here:
[userChrome.css.zip](https://github.com/Zonnev/elementaryos-firefox-theme/files/7292177/userChrome.css.zip)

**Comment by Zonnev** [comment]
Oh, one more comment: I installed Thunderbird in the Terminal with apt. I didn't install from the AppCenter because it's probably a flatpak version which doesn't work well with the userChrome I created.

**Comment by dre1080** [comment]
Thanks so much for this. Works perfectly! 
Tried it with flatpak, it works too. I had to place the `userChrome.css` in `~/.var/app/org.mozilla.Thunderbird/.thunderbird/[PROFILE]/chrome`

Thanks again!

**Comment by dre1080** [comment]
Hi! Any updates of latest version for Thunderbird on eOS 7? Plus dark theme variant as well?

**Comment by Zonnev** [comment]
Hello @dre1080, sorry for waiting but I have made some changes in the userChrome for the latest Thunderbird. Hope you like it! 

Download it here:
[userChrome.css.zip](https://github.com/Zonnev/elementaryos-firefox-theme/files/10941201/userChrome.css.zip)

**Comment by dre1080** [comment]
Wow! Thanks!

**Comment by Zonnev** [comment]
Maybe you've noticed, if not, I've made a repository for the elementary OS Thunderbird theme. You can check it out here: https://github.com/Zonnev/elementaryos-thunderbird-theme

Enjoy it!

**Comment by dre1080** [comment]
Awesome! Thanks!
