### ISSUE TITLE
It doesn't follow the system theme

### ISSUE THREAD

**Issue by ghost** [Zonnev/elementaryos-firefox-theme#150]
I don't know if it is supposed to but it doesn't follow the system theme. I can choose dark, light and system but system option doesn't follow the system theme. Is there anything I should be doing? 

Also, corners have [this weird issue](https://imgur.com/a/puH1IvM)

**Comment by Zonnev** [comment]
Hi, you are suppose to install [Pantheon Tweaks](https://github.com/pantheon-tweaks/pantheon-tweaks). When you set Pantheon Tweaks to dark mode, Firefox will switch to dark mode too. This setting makes dark mode available for non-elementary apps.

The corners are handled by Firefox, this issue I can not fix. But issue #144 talks about this. Latest post gives a link that you can read that they are working on making the corners better. Let's hope they will ;)

**Comment by ghost** [comment]
Well, GNOME theme doesn't do that weird corners so I thought it was a problem of yours. 

I would rather not to install Elementary tweaks, is there another option?

Link to GNOME theme: https://github.com/rafaelmardojai/firefox-gnome-theme

**Comment by Zonnev** [comment]
I just installed GNOME theme and it has square corners in elementary OS :
![Schermafdruk van 2021-10-23 18 25 37](https://user-images.githubusercontent.com/32688765/138564327-7a9fb382-5f50-45e9-805e-4f13a93ec22e.png)
I installed the GNOME theme in Firefox 93. By the way, on Firefox 95 Nightly, the corners of all theme's are square. This could be a mistake from Firefox.

> I would rather not to install Elementary tweaks, is there another option?

There is no other option when it comes to 'automatically' switch between dark and normal theme's. You have to switch dark mode 'on' manually in the customization panel.

**Comment by ghost** [comment]
You should have tried it on GNOME desktop but anyway. 

> There is no other option when it comes to 'automatically' switch between dark and normal theme's. You have to switch dark mode 'on' manually in the customization panel.

Alright then, thank you for your time and patience.
