### ISSUE TITLE
Top window corners don't have window border

### ISSUE THREAD

**Issue by vishnumad** [Zonnev/elementaryos-firefox-theme#151]
The dark gray border around the window doesn't seem to go around the window corners. This is especially noticeable against light backgrounds.
![Screenshot from 2021-11-11 00 41 27](https://user-images.githubusercontent.com/3137711/141250367-4695da7f-3faf-492a-8279-4322306c6b03.png)

**Comment by Zonnev** [comment]
Hello, yes I am aware of this issue. On Nightly it's even worse with black square corners. In issue #144 we are trying to make Firefox devs aware of this. For what I can read they are aware of it and are busy implementing a new way of dealing with these rounded corners. I don't see any results yet but hopefully soon something is going to change.

There is I think a problem that elementary OS has made it's own rounded corners for Odin which maybe is different than in Gnome and elementary OS does make rounded corners only for it's native apps, Firefox not included... So, if the rounded corners for Firefox on elementary OS Odin are going to improve, is not so sure.

**Comment by vishnumad** [comment]
Thanks, closing this since there's already an open issue
