### ISSUE TITLE
Tab bar flickering when overfilling

### ISSUE THREAD

**Issue by ded-ared** [Zonnev/elementaryos-firefox-theme#155]
Hello!
Today I noticed a strange glitch.

Tab bar is flickering when overfilled with tabs. It doesn't matter if the window is maximized or not.
(video is attached)

When I return to default Firefox theme, everything's fine.
Unfortunately, I can't say which update evoked that bug, because normally I try not to overfill my browser with tabs.
I tried to delete mozilla profile folder, to clean the browser, reinstall Firefox and get elementary theme from scratch - still no result.
Firefox is installed via "apt" in terminal. Last update (95).

Maybe there was such an issue before, but I couldn't find one.
If more info is needed, just say what kind of.

https://user-images.githubusercontent.com/58567667/146238381-9bf5a1e5-87cf-4f39-91ed-de0d2113f8e0.mp4

P.S. Sorry for my English. I tried my best.
Thanks for your theme! It's really great.

**Comment by Zonnev** [comment]
I can confirm and reproduce this issue, thanks for posting it. For now it's best to position the + button to the left of the tabs since this doesn't show problems when you use many tabs. I will try figure out the problem and fix it later and report it back here.

**Comment by ded-ared** [comment]
> For now it's best to position the + button to the left of the tabs since this doesn't show problems when you use many tabs. 

Oh, thanks! Such a simple workaround for a while.
Not so convenient as I used to, but at least no flickering.

**Comment by Zonnev** [comment]
I fixed this issue. You can position the + button to the right of the tabs again for your convinience after you installed the new userChrome.

**Comment by ded-ared** [comment]
Yes, it works perfectly.
Thank you so much!
