### ISSUE TITLE
Support for Firefox Multi-Account Containers

### ISSUE THREAD

**Issue by 2024-jcmljunior** [Zonnev/elementaryos-firefox-theme#156]
![image](https://user-images.githubusercontent.com/82642883/147704109-b0ba50d6-fcd0-48cd-a18c-94aae2d726c2.png)
The tab does not stay with the border color set according to the extent. The active window on the other hand appears border.
Would it be possible to remove the tabs and mark each window in a different way?

Maybe that way:
![image](https://user-images.githubusercontent.com/82642883/147705699-b1cf8c08-bf48-400a-8db2-32b7cac08075.png)

Firefox Multi-Account Containers:
https://addons.mozilla.org/pt-BR/firefox/addon/multi-account-containers/

**Comment by Zonnev** [comment]
I made the coloured line visible on not selected tabs, you can install the new userChrome.
![Schermafdruk van 2021-12-30 08 34 43](https://user-images.githubusercontent.com/32688765/147731048-a89555ba-c6fe-42cb-89f5-6ddf1c3410b5.png)

**Comment by 2024-jcmljunior** [comment]
![image](https://user-images.githubusercontent.com/82642883/147732080-3d8d25c5-d702-49b8-a6e1-d9c910793c89.png)
It was excellent.
Thank you!
