### ISSUE TITLE
Add a button layout for "no buttons"

### ISSUE THREAD

**Issue by jonseppanen** [Zonnev/elementaryos-firefox-theme#157]
Some instances/themes/combinations I use need me to use the titlebar, and this causes duplicate buttons. It would be great if the install script would have a "no buttons" option for this.

Thanks!

**Comment by Zonnev** [comment]
Hi, I added Titlebar Enabled in the installer script as option 9. It has no buttons in the navigation bar and shows only buttons in the title bar. You can now install option 9 in the installer of userChrome.

**Comment by jonseppanen** [comment]
Thanks so much!
