### ISSUE TITLE
How to use the purple (private mode) theme as the default theme?

### ISSUE THREAD

**Issue by ghost** [Zonnev/elementaryos-firefox-theme#158]

**Comment by Zonnev** [comment]
This can not be easily done with userChrome. You can of course [set firefox to always open in private mode](https://blog.scottlowe.org/2021/04/13/making-firefox-on-linux-use-private-browsing-by-default/). Maybe when I have time I will make a different userChrome for this.

**Comment by Zonnev** [comment]
I have added Private Mode Style in the installer. You can install it by selecting option 10 in the installer. Please note that Private Mode Style is now only available in default elementary OS window buttons layout.

**Comment by ghost** [comment]
This is awesome, thank you very much!
