### ISSUE TITLE
Dark mode Titlebar theme has Rounded Corners in the wrong places when not-maximized

### ISSUE THREAD

**Issue by chrisdotcode** [Zonnev/elementaryos-firefox-theme#159]
Thanks for continuing to develop this theme. I like titlebars, and it seems like the daytime variation of the theme looks just fine with them enabled. However, the dark version has rounded corners where a headerbar would be if there was no titlebar. A picture is the best description of this issue, so here it is:

![image](https://user-images.githubusercontent.com/1936426/152247765-17d86d68-ee9f-4b3b-9050-bde5fb3fcb60.png)

If you notice, right below the "x" in the leftmost hand corner, there's a rounded corner. I suspect that this is a hold-over from before the titlebar setting was added?

Also, it seems to work fine in fullscreen mode.

Thanks!

**Comment by Zonnev** [comment]
Hi, thank you for noticing this! I forgot all about dark mode rounded corners in the nav bar when making Titlebar Enabled but now it's fixed. You can install the new userChrome. Thanks again!

**Comment by chrisdotcode** [comment]
Can confirm as fixed. Thanks!
