### ISSUE TITLE
Install script refactoring

### ISSUE THREAD

**Issue by sempasha** [Zonnev/elementaryos-firefox-theme#161]
@Zonnev I'm working on new install script with features:

Automation:
1. Auto detect window controls layout;
2. Auto detect title-bar enabled/disabled/not configured;
3. Auto update `toolkit.legacyUserProfileCustomizations.stylesheets` preference;
4. Firefox profiles discovery with Flatpak installed instances support;
5. Optionally we could support Firefox forks, like LibreWolf (see #143).

This will improve user experience, user will need only one action - download and run installation script without answering any questions.

Configuration:
1. Ability to specify preferred controls layout;
2. Ability to force title-bar enabled/disabled style;
3. Ability to force private mode style;
4. Ability to specify target Firefox profile(s) where to install theme;
5. Ability to skip `toolkit.legacyUserProfileCustomizations.stylesheets` preference patch.

This will open ability to automate theme update by scheduling job like `curl https://github.com/.../install.sh [OPTIONS] | bash`.

I see, Flatpak installation was supported some time ago and support had been removed at [Sep 7 2021](https://github.com/Zonnev/elementaryos-firefox-theme/commit/734657e2ab079a0363804b07c2e1932817050c3f). Would you, please, tell me the reason, why?

**Comment by Zonnev** [comment]
Hi @sempasha, that install script sounds very nice and handy! I would be very happy to have a new and a more handy install script, since I was struggling with the existing script anyway. I just couldn't see the possiblities of a install script. Thanks for opening my eyes and offering your new script, I really appreaciate that!

Flatpak support was out because the userChrome's were not working so well the with the Flatpak version of Firefox. It would have been a great hassle to make a Flatpak version and test and maintain that too, so I skipped support of it.

I'm looking foreward to test your install script when it's finalised and ready to use. Thanks again!

**Comment by Zonnev** [comment]
>     4. Firefox profiles discovery with Flatpak installed instances support;
> 
>     5. Optionally we could support Firefox forks, like LibreWolf (see [LibreWolf support #143](https://github.com/Zonnev/elementaryos-firefox-theme/issues/143)).

Flatpak Firefox doesn't seem to work in recent elementary OS 6.1, but maybe it's my pc, I'm not sure. I can support LibreWolf only if it's the AppImage version, not the Flatpak version.

**Comment by sempasha** [comment]
@Zonnev, work is far from to be done, but I've submitted my progress, to let you see changes. 

My view on Flatpak support.

We could install theme stylesheets even for Flatpak installed Firefox. But we should warn user about limited support and make clear, that issues are possible. We also may involve user into contribution process using sentence like _We welcome contributions_ (see [warning example](https://github.com/sempasha/elementaryos-firefox-theme/blob/bd49f19cdbaf402d5be49836f235f01282d69083/install.sh#L90-L93))

**Comment by sempasha** [comment]
Hi @Zonnev I've made a new pull request #164.

To try new installation script, please, run command (it will download script from forked repo):

```bash
bash <(wget --quiet --output-document - "https://raw.githubusercontent.com/sempasha/elementaryos-firefox-theme/installation_script/install.sh")
```

**Comment by Zonnev** [comment]
Hi @sempasha I get an error running the command.
```
/dev/fd/63: line 1: syntax error near unexpected token `newline'
/dev/fd/63: line 1: `<!DOCTYPE html>'
```
Can you look at it? Thank you!

**Comment by sempasha** [comment]
Instead of posting link to RAW install.sh file, I'd posted link to HTML view of file.
Please try

```bash
bash <(wget --quiet --output-document - "https://raw.githubusercontent.com/sempasha/elementaryos-firefox-theme/installation_script/install.sh")
```

**Comment by Zonnev** [comment]
Thanks a lot for the work you've done! I have tested some points in the script:

- I have tested all button layouts and they are all working.
- I have tested the Titlebar Enabled Theme and its working too (when I enable the titlebar it installs the Titlebar Theme).
- I have found one mistake in the word **download**:  `Downalod stylesheets to chrome directory`
- I could not see an option to install the Private Mode Style, but I think there will be a separated install command for that in readme.
- The script ends with an error:
`/dev/fd/63: line 493: Enabled/prefs.js: The file or folder does not exist`

**Comment by sempasha** [comment]
> I have found one mistake in the word download: Downalod stylesheets to chrome directory

Will be fixed soon.

> I could not see an option to install the Private Mode Style, but I think there will be a separated install command for that in readme.

Please see updated [readme.md](https://github.com/sempasha/elementaryos-firefox-theme/blob/installation_script/readme.md), private mode installation described here. You can also try it right now by running

```bash
bash <(wget --quiet --output-document - "https://raw.githubusercontent.com/sempasha/elementaryos-firefox-theme/installation_script/install.sh") --private-mode-style
```



> The script ends with an error:
> ```/dev/fd/63: line 493: Enabled/prefs.js: The file or folder does not exist```

I need some more details about this issue. Could you please describe, how do you get this error (some steps to reproduce an issue). I guess you have browser installation with uncommon user profile directory, something like "~/.mozilla/firefox/Titlebar Enabled". Am I right?

**Comment by Zonnev** [comment]
> I guess you have browser installation with uncommon user profile directory, something like "~/.mozilla/firefox/Titlebar Enabled". Am I right?

Right!

**Comment by sempasha** [comment]
Ok, I'll try to fix it.

**Comment by sempasha** [comment]
- [x] `Downalod` typo fixed;
- [x] Spaces at user profile directory are supported now. 

You can try installing theme again, there should be no more issues with profile `~/.mozilla/firefox/Titlebar Enabled`.

**Comment by Zonnev** [comment]
@sempasha Perfect!
Can you look at [this issue](https://github.com/Zonnev/elementaryos-firefox-theme/pull/164#issuecomment-1053655611). There are some more grammar mistakes. Thanks!

**Comment by sempasha** [comment]
It is fixed already.
