### ISSUE TITLE
Use CSS import for CSS files

### ISSUE THREAD

**Issue by sempasha** [Zonnev/elementaryos-firefox-theme#165]
Hi, @Zonnev, what do you think about [CSS import](https://developer.mozilla.org/en-US/docs/Web/CSS/@import)? Seems this is the way for less code duplication. Proposal is to use single CSS file with base theme rules (lets say `base.css`) and several css files for each window controls layout with contents like:

```css
@import ./base.css;

/* rules for item control layout with !important directive */
...
```

**Comment by Zonnev** [comment]
Thanks for mentioning such a solution, I will think about it :)

**Comment by sempasha** [comment]
Let me know, if you will change theme files tree, I'll help with install script update.

**Comment by Zonnev** [comment]
@sempasha I have made a new branch called `newtree` which you can use for adjusting the install script in. 

I have a `base.css` and `userContent.css` file in the root and all button layouts as `userChrome.css` put in the specific folders. 
They need to come together in the `chrome` folder locally of course. 

The `userChrome.css` in the folders: `Private Mode Style` and `Titlebar Enabled`, both should **not** be together with `base.css` but only with `userContent.css` in the local `chrome` folder.  

I'd like to first test the installer in the new branch `newtree` before merging it all to master.

I hope you understand what I want and can do work adjusting the install script. Thanks a lot in advance!

**Comment by Zonnev** [comment]
> I'd like to first test the installer in the new branch `newtree` before merging it all to master.

I guess its faster to test the installer in your fork.

**Comment by Zonnev** [comment]
I've added `flatpak.css` in the root of `newtree` branch. 

`base.css` ` flatpak.css` `userContent.css` and a specific `userChrome.css` for a window control layout , should come together in the chrome folder of the flatpak directory locally.
