### ISSUE TITLE
Firefox 98.0 supports system dark mode, but the menu doesn't switch

### ISSUE THREAD

**Issue by diogopessoa** [Zonnev/elementaryos-firefox-theme#166]
When switching system to dark mode, Firefox automatically switches to dark theme, only the menu doesn't change.

![Captura de tela de 2022-03-10 07 41 29](https://user-images.githubusercontent.com/12633864/157650646-6484dc5b-ba75-4d6b-b42e-ad8980d394dd.png)

Software information:
elementary OS 6.1 Jólnir
Firefox 98.0 Flatpak

**Comment by Zonnev** [comment]
This issue is because you installed the Flatpak version which this theme doesn't support because of issues with the userChrome. Uninstall the flatpak version and please install Firefox with the Terminal typing: `sudo apt install firefox`. The theme has no issues with that version.

**Comment by diogopessoa** [comment]
Yes, the Deb version worked well. I hope that the Flatpak version will work well as soon as possible. 
Because to have Firefox updated in Deb version you need to add PPA repository.

Thank you for your support.

**Comment by Zonnev** [comment]
> I hope that the Flatpak version will work well as soon as possible.

I have made a flatpack version available. You can install the flatpak version of Firefox and install the theme. You don't have to uninstall the apt version to make the theme work on both versions.  Flatpak version looks a little different, see the window control buttons and the pull down menu's in the menubar. But besides those items the theme is the same as the main version. Good luck!
