### ISSUE TITLE
Tor Browser support

### ISSUE THREAD

**Issue by sempasha** [Zonnev/elementaryos-firefox-theme#170]
Tor Browser is based on Firefox. I've just tested that theme works well with Tor Browser. So Tor Browser support is possible.
Pull request is coming soon.
![Screenshot from 2022-03-23 13-51-44](https://user-images.githubusercontent.com/1610465/159660271-29e43468-b679-4ef3-adb2-2905507be3fd.png)

**Comment by Zonnev** [comment]
Thank you for testing Tor Browser with my theme :)

**Comment by sempasha** [comment]
@Zonnev, thank you for awesome theme, it's my pleasure to contribute this project.

**Comment by Zonnev** [comment]
@sempasha  Hi, Tor Browser has a problem with the install script: issue #185 
Thanks!
