### ISSUE TITLE
Theme developer guide

### ISSUE THREAD

**Issue by sempasha** [Zonnev/elementaryos-firefox-theme#175]
Hi, @Zonnev, seems that Firefox theme development is not a trivial task. It would be nice to have some initial guide about Firefox theme development process. This way project will be more open for potential contributors.

**Comment by Zonnev** [comment]
Hi, it's been asked before and I still have to clean up `base.css` a bit so contributors will see their way in it more easy. I will start making a theme developer guide soon, it's not so difficult.

**Comment by Zonnev** [comment]
I have just added [CONTRIBUTING.md](https://github.com/Zonnev/elementaryos-firefox-theme/blob/elementaryos-firefox-theme/CONTRIBUTING.md) as a start guide for developers/contributers. If something is missing, I'm glad to add it.

**Comment by sempasha** [comment]
Seems it is OK. I have nothing to add. Thank you.
