### ISSUE TITLE
tab media playing not visible in dark mode

### ISSUE THREAD

**Issue by Soljanka** [Zonnev/elementaryos-firefox-theme#178]
steps to reproduce:
1. open any video platform and play a video
2. once the media is playing it should say so in the tab ("Wiedergabe" in german)

this is visible in light mode
![Bildschirmfoto von 2022-05-18 21 50 56](https://user-images.githubusercontent.com/7444116/169148309-4215ee7c-6a6a-498f-840e-167e3c4846d2.png)

but not in dark mode
![Bildschirmfoto von 2022-05-18 21 51 40](https://user-images.githubusercontent.com/7444116/169148437-e01e9825-6c4e-4fe2-9446-dc156612eabd.png)

**Comment by Zonnev** [comment]
Thank you for showing me this issue! It's solved it in the new flatpak.css

**Comment by Soljanka** [comment]
Thank you for the fix, I can confirm that "Wiedergabe" is now visible in dark mode aswell:
![Bildschirmfoto von 2022-05-19 08 58 03](https://user-images.githubusercontent.com/7444116/169230375-699fe9c2-8032-43a3-b788-68076d71ab65.png)
