### ISSUE TITLE
marked checkboxes in clear history menu (ctrl + shift + del) hardly visible

### ISSUE THREAD

**Issue by Soljanka** [Zonnev/elementaryos-firefox-theme#179]
steps to reproduce:
1. Open the menu to clear the browser history
2. Check whatever you want to clear

the marked checkboxes are hardly visible in dark mode
![Bildschirmfoto von 2022-05-18 22 29 21](https://user-images.githubusercontent.com/7444116/169150609-4a39a254-5933-4a37-bd38-a3595b891d63.png)

and nearly invisble in light mode
![Bildschirmfoto von 2022-05-18 22 30 04](https://user-images.githubusercontent.com/7444116/169150656-d182a2fd-6dc5-46db-90f5-09be39c29db8.png)

A quick and dirty fix I could think of is to change the background color. I changed the default theme in the flatpak.css (line 30)
`    background-color: white !important;`
to lightgrey and could at least see what boxes are checked
![Bildschirmfoto von 2022-05-18 22 35 33](https://user-images.githubusercontent.com/7444116/169151527-eb5cceda-b52a-4fd9-9a83-296bec76cf96.png)
and line 200 
`    background-color: rgba(68,68,68,1) !important;`
to darkgrey
![Bildschirmfoto von 2022-05-18 22 42 21](https://user-images.githubusercontent.com/7444116/169152554-a1f16ba1-cc58-460f-a248-97b789f2f1c5.png)

There are probably cleaner RGB-values that would fit the theme better. Ideally I would like to have the blue checkboxes here aswell, but I can't figure out why they aren't used in this menu
![Bildschirmfoto von 2022-05-18 22-45-22](https://user-images.githubusercontent.com/7444116/169152811-4e6d51c7-3ab8-4952-ae1a-7a1781a2c217.png)

**Comment by Zonnev** [comment]
I have made all checkboxes the same now, thank you for showing me this issue. It's solved in the new flatpak.css and base.css.

**Comment by Soljanka** [comment]
Wow man, that was quick. Thank you a lot for the fix. Both light and dark mode now have nice looking checkboxes. I think the issue can be closed.
![Bildschirmfoto von 2022-05-19 08 54 56](https://user-images.githubusercontent.com/7444116/169229524-266e66bc-5c54-494b-bc58-e99659a9743e.png)
![Bildschirmfoto von 2022-05-19 08 55 26](https://user-images.githubusercontent.com/7444116/169229539-28770e10-cd56-47cd-8bf2-5f9197c3a202.png)
