### ISSUE TITLE
Search bar (ctrl + f) is white in dark mode

### ISSUE THREAD

**Issue by Soljanka** [Zonnev/elementaryos-firefox-theme#180]
The search bar is always white. This looks fine in light mode, but not in dark mode. I am not sure about private mode, the white does not feel out of place, but maybe a purple search bar would also fit better into the theme.

![Bildschirmfoto von 2022-05-19 13 36 16](https://user-images.githubusercontent.com/7444116/169284703-71a2e033-0943-4e13-8a04-9961b29cf613.png)

![Bildschirmfoto von 2022-05-19 13 36 50](https://user-images.githubusercontent.com/7444116/169284840-58775edd-b80e-45a5-af09-68db64f2ecef.png)

**Comment by Zonnev** [comment]
I've made the find bar dark for flatpak dark mode. Thanks again!

**Comment by Soljanka** [comment]
Can confirm, it's dark now. Thank you a lot for the quick fixes.
![Bildschirmfoto von 2022-05-19 14 08 55](https://user-images.githubusercontent.com/7444116/169289996-6164b8e7-d24b-4d70-aeec-f5d1527b6be2.png)
