### ISSUE TITLE
Website information (ctrl + i) does not follow dark theme

### ISSUE THREAD

**Issue by Soljanka** [Zonnev/elementaryos-firefox-theme#181]
As seen in the screenshot, the menu for the website information (ctrl + i) does not follow the dark theme
![Bildschirmfoto von 2022-05-19 21 34 23](https://user-images.githubusercontent.com/7444116/169388707-f61ea230-0357-4843-81c7-33271863d1cc.png)

I am not sure if this can be fixed aswell, but it would be nice. I really love your theme and this is probably the last issue I will create since everything else just looks fine :)

**Comment by Zonnev** [comment]
I'm sorry to mention that this is one of the things in the flatpak version of Firefox that is limited and can not be adjusted. Also the Library window (where History, Downloads and Bookmarks live) is not themed dark in the flatpak version of Firefox. Flatpak Firefox is just not as perfect as the apt version.

**Comment by Soljanka** [comment]
Well if it is not possible to change this in the flatpak version we can close this issue. It is just a minor inconvenience anyway ;)
