### ISSUE TITLE
mute tab not visible in dark mode

### ISSUE THREAD

**Issue by Soljanka** [Zonnev/elementaryos-firefox-theme#182]
steps to reproduce
1. have a tab that is playing media
2. hover over the tab
3. the tab should have a speaker icon on the right site to mute the tab

the tab does have the speaker icon in light mode
![Bildschirmfoto von 2022-05-24 22 46 37](https://user-images.githubusercontent.com/7444116/170129329-ef0e8d26-4d64-46b1-bbad-fc6d7bc9e652.png)

but not in dark mode (well it does have the icon, but it's hardly visible)
![Bildschirmfoto von 2022-05-24 22 48 17](https://user-images.githubusercontent.com/7444116/170129588-6a9d08d0-40b2-450a-89fb-2bb96eff03f1.png)

**Comment by Zonnev** [comment]
Thanks again for finding these issues! I have solved it in the new flatpak.css

**Comment by Soljanka** [comment]
I just updated the theme and the icon is now visible in dark mode too, thanks for the quick fix.
