### ISSUE TITLE
window control buttons not visible in dark mode anymore

### ISSUE THREAD

**Issue by Soljanka** [Zonnev/elementaryos-firefox-theme#183]
The latest firefox update (version 101) broke the window control buttons (close, maximize, ...) in dark mode as seen in the attached screenshot:
![Bildschirmfoto von 2022-06-01 10 11 29](https://user-images.githubusercontent.com/7444116/171359041-4dc13e3c-f0fb-4889-a973-619f900e23ac.png)

**Comment by Zonnev** [comment]
I solved this issue in the latest flatpak.css, thanks again!

**Comment by Soljanka** [comment]
I just updated the theme and window control buttons are visible in dark mode again, thanks for the fix
