### ISSUE TITLE
Installer script keeps installing Titlebar Enabled even when titlebar is disabled in Tor Browser

### ISSUE THREAD

**Issue by Zonnev** [Zonnev/elementaryos-firefox-theme#185]
@sempasha Hello, I found a bug in the installer, can you look at it? I once installed the Titlebar Enabled script but now the "normal" script doesn't revert it, even when I disabled the titlebar in Tor Browser. The "normal" script keeps installing the userChrome from the Titlebar Enabled folder. Hope you can find the problem, thank you in advance!

Edit: Other versions of Firefox don't have this issue, it's only for Tor Browser.

**Comment by sempasha** [comment]
@Zonnev, confirmed. This is because Firefox used to specify titlebar visibility with option `(boolean) browser.tabs.drawInTitlebar` until version 95, since 95 option is `(number) browser.tabs.inTitlebar`. Tor Browser based on Firefox 91 ESR. I'll update install script in few days.

**Comment by Zonnev** [comment]
Thank you for updating the script so fast!
