### ISSUE TITLE
Snap install of Firefox in eOS 7.0

### ISSUE THREAD

**Issue by Zonnev** [Zonnev/elementaryos-firefox-theme#189]
@sempasha I noticed in elementary OS 7.0 early builds that by running command `sudo apt install firefox` it will automatically install Firefox Snap version, **which is the same as the Flatpak version so no need for a new css file.** 

So maybe in the future when 7.0 is final, we need to adjust the install script to cover Snap installations  too. Or maybe it can be done now? Then make it that the script collects `flatpak.css` `base.css` `userChrome.css` and `userContent.css` for the Snap version of Firefox. I'm not in a hurry but thank you in advance for your help :)

**Comment by sempasha** [comment]
@Zonnev I have only stable Elementary OS installation, so I'll try adjust script for plain snap installation and later, when I'm done, I'll ask you to test.
