### ISSUE TITLE
Tab bar acting wonky in latest Firefox update

### ISSUE THREAD

**Issue by alaiterg** [Zonnev/elementaryos-firefox-theme#192]

**Comment by alaiterg** [comment]
![imagen](https://user-images.githubusercontent.com/22871434/212413024-f06cd8cf-2d79-412c-b4b7-56d5600404cf.png)
The tab is no longer in line with the tab bar as seen above

**Comment by Zonnev** [comment]
You should update the installation because this issue has been tackled awhile ago and isn't present anymore. Copy and paste this in the Terminal:
`bash <(wget --quiet --output-document - "https://raw.githubusercontent.com/Zonnev/elementaryos-firefox-theme/elementaryos-firefox-theme/install.sh") --update`

**Comment by Zonnev** [comment]
Did updating the installation of the theme help?

**Comment by alaiterg** [comment]
Thanks for letting me know!! It worked :)

**Comment by sempasha** [comment]
@alaiterg do you use increased text size?

I have same issue with text size 1.36
![Screenshot from 2023-01-16 21-15-01](https://user-images.githubusercontent.com/1610465/212723528-fd432936-aa9b-4571-af30-355eb399d314.png)

![Screenshot from 2023-01-16 21-08-52](https://user-images.githubusercontent.com/1610465/212723584-3de67c90-6789-4efd-8b4d-d73839563715.png)

While setting text size to 1.37 makes tabs properly positioned
![Screenshot from 2023-01-16 21-09-48](https://user-images.githubusercontent.com/1610465/212723563-b4060d99-8eb4-4ae7-a753-1158d8248aed.png)

**Comment by alaiterg** [comment]
That seems to have solved it! I had my text size set to 1.15. Thanks for the help

**Comment by alaiterg** [comment]
It was working before the update which leads me to believe that Firefox made a change with the formatting, but after some tweaking with the chrome CSS, I was able to fix it by adjusting height and `.toolbar-items {min-height}` under `#TabsToolbar`

**Comment by Zonnev** [comment]
I fixed this issue in latest update of the theme by adding `max-height` to the tabs. Now tabs stay inside the tabs toolbar while the text is able to grow bigger by adjusting text size in elementary OS.  @alaiterg Update the theme like I showed you before :) Enjoy.

**Comment by alaiterg** [comment]
Worked like a charm, thank you so much! :)
