### ISSUE TITLE
A way to revert the changes caused by the script

### ISSUE THREAD

**Issue by akashdalvi11** [Zonnev/elementaryos-firefox-theme#197]
Hi, I was trying to find a way by which we can restore firefox UI to it's previous settings. from what I understand, the install script creates 'userChrome.css' and 'userContent.css' under "firefox/browser/chrome". 
Will it be sufficient to delete those files to return to the "exact" state of firefox as it was before. It would be great if you include this info in the readme, as it will allow people to try it out without being concerned. 

PS: it's simply beautiful, love it!

**Comment by Zonnev** [comment]
Thanks for reporting the issue. I've added uninstall info in the readme.
