### ISSUE TITLE
PWA Theme

### ISSUE THREAD

**Issue by edwardally** [Zonnev/elementaryos-firefox-theme#199]
Is that possible to theme on the PWA?

![image](https://github.com/Zonnev/elementaryos-firefox-theme/assets/1024003/4462a65b-3c83-4326-9391-bf51fac2dde5)

**Comment by Zonnev** [comment]
Hello, looking at your picture I understand the window controls are not displaying like Firefox browser but I'm sorry, I will not theme extensions and/or add-ons...
