### ISSUE TITLE
Tab bar dims when window loses focus

### ISSUE THREAD

**Issue by nevillepark** [Zonnev/elementaryos-firefox-theme#200]
Hi, I rarely remember to run the update script so I'm afraid I'm not sure when this changed, but I recently updated the theme and now the tab bar becomes dimmed when the Firefox window isn't active.  

With focus:
![Screenshot from 2024-01-23 14 48 36](https://github.com/Zonnev/elementaryos-firefox-theme/assets/16054979/75acaeec-5e7c-4096-95ea-8a7b314eb144)

When another window is focused:
![Screenshot from 2024-01-23 14 48 47](https://github.com/Zonnev/elementaryos-firefox-theme/assets/16054979/28c449b5-f4cc-499b-8707-c893330a676b)

Screen recording:
https://github.com/Zonnev/elementaryos-firefox-theme/assets/16054979/31fedab2-b3de-4067-adf6-fd3c31e86230

(This is with an application launcher, but it happens when focusing on any other kind of window, including the alt+tab window switcher and ordinary application windows.)

Is this behaviour intended? Or is it a system settings issue?

**Comment by Zonnev** [comment]
Hello! Thank you for reporting this issue. I had some difficulties finding out what this issue caused but I have managed to fixed it in the latest update! You can now update or reinstall the theme.

**Comment by nevillepark** [comment]
Thank you so much!
