### ISSUE TITLE
Theme alert dialogs

### ISSUE THREAD

**Issue by arshubham** [Zonnev/elementaryos-firefox-theme#22]
![image](https://user-images.githubusercontent.com/14235191/54698373-32514100-4b55-11e9-9960-b4d7e2a8400c.png)

Ref: https://gist.github.com/RavinduL/bbd01d88f36ca04f9958b4be1b306446

**Comment by Zonnev** [comment]
I think I'm not capable to theme these dialogs. Though I feel they are missing an alert icon. But if there is no icon in the dialog, I can not place an icon and change that icon. Sorry arshubham , but I think I have to pass this request...

**Comment by arshubham** [comment]
I dont expect an icon. If it is just possible to theme the buttons and dialog color and borders in elementary style that  would be great
