### ISSUE TITLE
Bash script is not working

### ISSUE THREAD

**Issue by ntassani** [Zonnev/elementaryos-firefox-theme#28]
Any help for install this amazing theme?
Thanks!

**Comment by Zonnev** [comment]
Just copy the bash script line into the terminal and press enter. Maybe you need to install cURL? For me, the bash script does work but it does give me a warning.

**Comment by kunalkushwaha** [comment]
remove ``&& touch "$FILE" from  [install.sh](https://github.com/Zonnev/elementaryos-firefox-theme/blob/master/install.sh#L14)  and it will work. 

$FILE is initialized and is not required.

``` bash
mkdir -p "$(dirname "$THEMEPATH")" 
curl -K -O $URLPATH >> $THEMEPATH
```
