### ISSUE TITLE
History / Search drop down not dark

### ISSUE THREAD

**Issue by joedborg** [Zonnev/elementaryos-firefox-theme#29]
The bottom part of the history / search drop down appears to still be light.

![Screenshot from 2019-06-28 14-45-39](https://user-images.githubusercontent.com/1426404/60367364-a2bcf900-99b3-11e9-8510-e1d42ee13eec.png)

**Comment by Zonnev** [comment]
Strange, I don't have this bar under my search drop. Is it an extension?

**Comment by joedborg** [comment]
> Strange, I don't have this bar under my search drop. Is it an extension?

No, it's stock. Confirmed I get the same with Ubuntu 18.04 too.

**Comment by Zonnev** [comment]
@joedborg Thanks for pointing out this bug. I have fixed it )

**Comment by joedborg** [comment]
Looking great!  Thanks.
