### ISSUE TITLE
Current Tab overlaps search suggestion popover in Latest nightly

### ISSUE THREAD

**Issue by arshubham** [Zonnev/elementaryos-firefox-theme#30]
Version 	70.0a1
Build ID 	20190819095406

![Screenshot from 2019-08-19 23-13-46](https://user-images.githubusercontent.com/14235191/63287262-8f554c80-c2d7-11e9-9acc-9a2312139075.png)

**Comment by Zonnev** [comment]
@arshubham Thanks for noticing this bug. It's fixed now.
