### ISSUE TITLE
Help: the bash script adds css to old userChrome!

### ISSUE THREAD

**Issue by Zonnev** [Zonnev/elementaryos-firefox-theme#32]
Can someone help me with a new bash script, since the old one duplicates or moves the new userChrome within the old userChrome document. It made the file twice as large...

Thanks in advance!!!

**Comment by sempasha** [comment]
Hi, can you please add more details on script, is it installation script. Do you mean [install.sh](/Zonnev/elementaryos-firefox-theme/commit/824fc31249bad80f13cf873d557946d105240ed7#diff-3fbb47e318cd8802bd325e7da9aaabe8)?

**Comment by Zonnev** [comment]
Yes thats the file. When using the install.sh to install a new userChrome.css, the new css code _adds_ into the old userChrome.css. Result is double css code in the userChrome file. What I would like to have is an install.sh that completely _replaces_ the old userChrome.css. If you could manage that, I would be very grateful, it would simplify the installing process for users. Many thanks in advance!

**Comment by Zonnev** [comment]
@sempasha Many thanks for the installer! But... when it searches for the default folder of Firefox it picks the wrong folder. I'm sorry to say, but could you look into it one more time? Thank you.

**Comment by Zonnev** [comment]
The right folder has "default-release" in it.

**Comment by sempasha** [comment]
Could you please show contents of ~/.mozilla/firefox/profile.ini file?

**Comment by Zonnev** [comment]
[Install4F96D1932A9F858E]
Default=tz37qdyy.default-release
Locked=1

[Profile1]
Name=default
IsRelative=1
Path=b5yd1hth.default
Default=1

[Profile0]
Name=default-release
IsRelative=1
Path=tz37qdyy.default-release

[General]
StartWithLastProfile=1
Version=2

**Comment by sempasha** [comment]
You have two profiles here:

  1. `b5yd1hth.default` which as marked as `Default=1`;
  2. and another one is `tz37qdyy.default-release`.

Installation script you have before, always selects profile, marked as `Default`. Current script has same logic.

We have three options here:

  1. Do not modify script and install userChrome.css to default profile only (current behaviour);
  2. Modify script to install `userChrome.css` to all user profiles;
  3. Modify script to ask user, which profile to install `userChrome.css`

My view is to ask user. What is your opinion on that case?

**Comment by Zonnev** [comment]
I'm afraid most users don't know about the profiles. Like me, I installed FF beta, uninstalled it, but it gave me a second profile not known to me. 

So I want to choose option 2, because a user wants the theme to work, no matter which profile is default. Thanks for your time and effort. Option 2 it is.

**Comment by sempasha** [comment]
Ok, got it.

**Comment by sempasha** [comment]
That's done. Thank you for accepting pull requests.

**Comment by Zonnev** [comment]
Thanks @sempasha, almost done! 

`Install ElementaryOS Firefox Theme (https://github.com/Zonnev/elementaryos-firefox-theme)

  1. Check Firefox installation ...  done
  2. Search for firefox profiles ... 2 profiles found
  3. Install theme at profile path /home/michael/.mozilla/firefox/tv2kft7w.default:
     - Ensure directory 'chrome' ... done
     - Create file 'chrome/userChrome.css' ... done
  4. Install theme at profile path /home/michael/.mozilla/firefox/tv2kft7w.default:
     - Ensure directory 'chrome' ... done
     - Create file 'chrome/userChrome.css' ... done

Done, restart Firefox, please.`

Thats my output. As you can see it installs in the same path twice. Please adjust that and we are good to go! Thanks.

**Comment by Zonnev** [comment]
That's it!

**Comment by sempasha** [comment]
@Zonnev, done.
