### ISSUE TITLE
Must use Nightly style for both nightly firefox and developer edition firefox

### ISSUE THREAD

**Issue by JARVIS-AI** [Zonnev/elementaryos-firefox-theme#37]
Thanks for added nightly version

I pulled a request for clarification in Readme to show users about this

As I don't know about nightly version works on Firefox Dev too so I edited the chrome style by myself and waste my time.
But you have worked on it before with great polish

As you can see in normal version there is another bar under tabbar that is not useful for any case, its just a bar - empty bar

Thanks for great theme
Love Elementary OS

> Normal on Firefox Dev

![Screenshot from 2019-11-08 12-57-22@2x](https://user-images.githubusercontent.com/8873215/68465283-6e8dfa80-0227-11ea-892e-43256c9205ad.png)

> Nightly on Firefox Dev

![Screenshot from 2019-11-08 13-02-21@2x](https://user-images.githubusercontent.com/8873215/68465619-0986d480-0228-11ea-830e-5f7df211c0ef.png)

**Comment by Zonnev** [comment]
Thank you!

**Comment by Zonnev** [comment]
There is (for now) no difference in userChrome between Nightly, DE and standard Firefox.
