### ISSUE TITLE
[Feature Request] Increase Tab Contrast

### ISSUE THREAD

**Issue by reece146** [Zonnev/elementaryos-firefox-theme#46]
Thanks for sharing this theme!

One thing I've noticed: there does not seem to be enough contrast between tabs. Maybe this is a dark theme thing only? 4K only thing? 

![Screenshot from 2019-11-15 16-21-27](https://user-images.githubusercontent.com/6394378/68976575-137a7b80-07c4-11ea-83ee-de1c19e25946.png)

Suggestions:

1.) Make the in-focus background tab colour different from out-of-focus tabs
2.) Make the line drawn between tabs "stronger" via colour choice and/or weight/thickness.

Great stuff!

**Comment by Zonnev** [comment]
The colours of the dark mode is the same as elementary tweaks dark mode. I don't want to change that. But I did a change by applying a box shadow around the active tab and darken the tabs bar a bit more. I find these changes very minor and they don't help much with the contrast. The active tab has a close button, that's how you can identify it. I will upload the new userChrome with the box shadow around the active tab, plus the darken tabs bar, so you can see if it helps you out a bit.

**Comment by reece146** [comment]
That does help a little compared to the way it was. 

I understand about not wanting to modify the theme too much away from the elementary standard. You don't want to be chasing changes every time there is an update.

Thanks!
