### ISSUE TITLE
Double title bar

### ISSUE THREAD

**Issue by wout** [Zonnev/elementaryos-firefox-theme#47]
Firefox (70.0.1) is showing a title bar above the menu bar.

![image](https://user-images.githubusercontent.com/107324/69007186-cbca3000-093a-11ea-86fe-9f7f932cc627.png)

How can I get rid of the title bar?

**Comment by Zonnev** [comment]
Menu > Customize > at the bottom uncheck "Title Bar"

**Comment by wout** [comment]
Thanks!
