### ISSUE TITLE
tab bar elements on top of address history list

### ISSUE THREAD

**Issue by mozartilize** [Zonnev/elementaryos-firefox-theme#48]
when you have many tabs which make tab bar overflow, the navigate button element will be on top when open address history of address bar (right on the cursor in the picture below)

![Issues · Zonnev-elementaryos-firefox-theme - Firefox Developer Edition_059](https://user-images.githubusercontent.com/26346270/69535269-248a7000-0fae-11ea-9b97-a3430d737b7c.png)

**Comment by Zonnev** [comment]
I've fixed it for standard Firefox, but in Nightly it doesn't seem to work. I know it's setup differently but today Nightly doesn't overwrite the z-index for this element. I will update only the standard userChrome. Thanks for discovering this issue.

**Comment by mozartilize** [comment]
unluckily I use firefox DE

**Comment by Zonnev** [comment]
The scrollbox indicators in Nightly an Developer can not be directly adjusted by userChrome. Maybe in the future they will be, I dont know yet. In the meantime I suggest you to use the Megabar. Installation of the Megabar is described in the readme.

**Comment by Zonnev** [comment]
This bug is opened here: https://bugzilla.mozilla.org/show_bug.cgi?id=1575507
