### ISSUE TITLE
Tabs don't use the entire tabstrip

### ISSUE THREAD

**Issue by arshubham** [Zonnev/elementaryos-firefox-theme#5]
Firefox 57.0.a1 There is a lot space available at the end.
![image](https://user-images.githubusercontent.com/14235191/52724241-02060800-2fd5-11e9-8acc-93990c8ff7cd.png)

**Comment by Zonnev** [comment]
Hello, I did preserve this space for the private mask icon in private mode.

**Comment by arshubham** [comment]
I don't think it is that important to show the private mask. It is already shown in the new tab window as well as favicon.

**Comment by NeoMahler** [comment]
I agree with @arshubham, the tab already has that icon. I think removing it altogether is a good idea.

**Comment by Zonnev** [comment]
When I use the tab loading a site, the private icon is gone. Then there is no way to see you are in private mode. So I don't know yet...

**Comment by NeoMahler** [comment]
Could the address and tab bar be coloured with a purple tone when in
private mode? This would solve the issue and still be elementary-like.

El ds., 20 abr. 2019, 01:41, Zonnev <notifications@github.com> va escriure:

**Comment by Zonnev** [comment]
I wish there was a possibility for colouring in private mode but there are no selectors for private mode anymore in Firefox.

**Comment by NeoMahler** [comment]
Oh, that's a pity. Then, could it be somehow moved to the address field,
next to either the magnifier icon or the dropdown arrow? Just throwing
ideas around! :P

Missatge de Zonnev <notifications@github.com> del dia ds., 20 d’abr. 2019 a
les 12:18:

**Comment by Zonnev** [comment]
Again, I wish to do it but the private icon appears to be on top of everything. When I would add it to the url bar, I have to make a space for it, **only for private mode**. Firefox doesn't care for 'private mode only' adjustments. Yes, it's a pity...

**Comment by NeoMahler** [comment]
aw dang. Well, you're doing a great job with the theme. When I have free time, let's see if I can help out with something!

**Comment by Zonnev** [comment]
@NeoMahler I found a way to change colours in private mode :) I will work on it, stay tuned for a new userChrome.
