### ISSUE TITLE
Replace firefox's bookmarks icon with the one in Epiphany

### ISSUE THREAD

**Issue by ChrisP4** [Zonnev/elementaryos-firefox-theme#50]
Epiphany has a yellow star as a bookmarks icon, which I think I've seen in other places in elementary as well. The image pretty much shows it.

![Captura de pantalla de 2019-12-03 21-45-50](https://user-images.githubusercontent.com/14283056/70084152-736f7f80-1616-11ea-834b-e5f0f250599d.png)

**Comment by Zonnev** [comment]
Sorry, I won't change the bookmarks icon because firstly the bookmark menu icon of Firefox isn't standard in the toolbar (one has to put it there through the customization panel) and secondly it won't look good with the other icon's of Firefox functions/extensions/addons.
