### ISSUE TITLE
Is it possible to hide the tab bar?

### ISSUE THREAD

**Issue by Maccer1** [Zonnev/elementaryos-firefox-theme#52]
I'm using an extension to have my tabs on a sidebar so I would like to hide the tab bar. At the moment I've tried adding to your UserChrome.css file the line `#TabsToolbar { visibility: collapse !important; }` which actually hides the tabs however there's still a gray background. Is there any way to hide it?

Thanks :)

**Comment by Zonnev** [comment]
Adjust 30px to 0px on line 124:
```
#navigator-toolbox {
  padding-bottom: 0px !important; /* makes room for the tab bar */
}
```
Good luck!
