### ISSUE TITLE
Blank bar with Firefox 71.0

### ISSUE THREAD

**Issue by joedborg** [Zonnev/elementaryos-firefox-theme#53]
Since updating to Firefox 71.0, there's a blank space between the rendered page and top bar:

![Screenshot from 2019-12-10 13 32 01](https://user-images.githubusercontent.com/1426404/70557816-97205180-1b51-11ea-947d-4bd34f393153.png)

**Comment by Zonnev** [comment]
Hmm seems you did not update your userChrome. Install the latest userChrome from the main page.

**Comment by joedborg** [comment]
You're right, thanks.  I did download the new version, but it seems Firefox had created a new profile dir in the mean time.

**Comment by Zonnev** [comment]
Next time there is an update, you could use the one line installer because it automatically installs userChrome in all existing profile directories. Just copy the line and paste it in your terminal.
