### ISSUE TITLE
Grey bar under the tab bar on Firefox 71

### ISSUE THREAD

**Issue by TheLinuxEXP** [Zonnev/elementaryos-firefox-theme#55]
On Firefox 71, there is a grey bar appearing under the tab bar.
It seems that reducing the padding to 0 on line 124 fixes it.

**Comment by Zonnev** [comment]
Its already mentioned in issue #53. Download the new userChrome and put it in your profile directory. If you have more profiles, then its better to use the one line script since it will put the userChrome in all your existing profile directories.

**Comment by TheLinuxEXP** [comment]
Thanks, I'll close the issue :)
