### ISSUE TITLE
Dark URL bar used in light theme

### ISSUE THREAD

**Issue by qgreen63** [Zonnev/elementaryos-firefox-theme#56]
The URL bar has a dark background when not using the dark theme, but the text remains themed for the light theme, making it both ugly and hard to see

**Comment by Zonnev** [comment]
It's because the url bar of the light mode in Firefox is themed by elementary. I could change that, I didn't tried it before because in early Firefox versions the url bar wouldn't have rounded corners when theming it. I will look into it.

**Comment by Zonnev** [comment]
Also, use the standard mode or the dark mode, not the light mode in Firefox because the light mode is not themed in this userChrome.

**Comment by Zonnev** [comment]
Light mode does now have a light url bar. Make sure to use the latest userChrome on the main page.
