### ISSUE TITLE
[feature request] elementary thunderbird theme

### ISSUE THREAD

**Issue by queeup** [Zonnev/elementaryos-firefox-theme#57]
Is it possible to make elementary thunderbird theme? I really love to see looking good thunderbird on my elementary OS.

**Comment by Zonnev** [comment]
I tried to work on an elementary theme for Thunderbird but I got stuck trying to move the tab bar under the tool bar. I've done that but Thunderbird removes the tool bar when it is on preferences pages. Result was that the tab bar got stuck on top of the preferences pages making the pages unreadable. Basically I can only theme the tab bar to elementary standards which is not enough in my vision. So I won't theme Thunderbird untill I find a solution but that won't be anytime soon.

**Comment by queeup** [comment]
OK, I understand. Feel free to close this issue. Thank you for your explanation.

**Comment by Zonnev** [comment]
I can share with you my userChrome for Thunderbird. It looks like this:
![Schermafdruk van 2019-12-24 21 22 31](https://user-images.githubusercontent.com/32688765/71424641-d2fc0080-2693-11ea-9e0e-7105a555ad2b.png)
I only themed the tab bar and the menu icon, but it already looks better integrated in elementary OS than the default theme. You can download the zipped userChrome here:
[userChrome.css.zip](https://github.com/Zonnev/elementaryos-firefox-theme/files/3999013/userChrome.css.zip)

**Comment by queeup** [comment]
Perfect. Thank you. I will use it.

**Comment by queeup** [comment]
Just one last question: What if I use without title bar?
![2019-12-25 00-38-43 ekran görüntüsü](https://user-images.githubusercontent.com/87835/71425576-afdf4a00-26af-11ea-8a34-0bece4e1c0c1.png)


Can you do something about height and close button to the right corner?

**Comment by Zonnev** [comment]
Thunderbird without title bar and max and close buttons to the right:
![Schermafdruk van 2019-12-25 14 13 53](https://user-images.githubusercontent.com/32688765/71446209-15b7ea00-2721-11ea-8cff-b2073ad73df4.png)

Download this userChrome:
[userChrome.css.zip](https://github.com/Zonnev/elementaryos-firefox-theme/files/4000479/userChrome.css.zip)

**Comment by queeup** [comment]
Excuse me, I was confused. I wanted to tell you close button left, toggle fullwindow button right actually. Like elementary default.

**Comment by Zonnev** [comment]
Your in luck because I've made this already.

![Schermafdruk van 2019-12-25 15 15 10](https://user-images.githubusercontent.com/32688765/71683492-fcebac00-2d92-11ea-8adf-623a6d27da19.png)

Download:
[userChrome.css.zip](https://github.com/Zonnev/elementaryos-firefox-theme/files/4016846/userChrome.css.zip)

**Comment by Zonnev** [comment]
If you use the menu bar sometimes I fixed the mess a bit by moving it under the tab bar.
Add this css into the userChrome file:
```
#mail-toolbar-menubar2 {
  -moz-box-ordinal-group: 2;
  border-bottom: 1px solid #b6b6b6 !important;
}
```
There was no way to have a functional menu bar with the window control buttons in it, that's why I moved it under the tab bar...

**Comment by queeup** [comment]
Sweet. Thank you. I disabled menu bar but just in case I added your suggestion. Unfortunately `Alt` key not working for displaying menu bar like in firefox. Anyways, menu bar items also in hambuger menu. That's good enough.
