### ISSUE TITLE
[encahncement] [feature request] Make the menu bar (appears by pressing the Alt key) visually consistent

### ISSUE THREAD

**Issue by ChrisP4** [Zonnev/elementaryos-firefox-theme#59]
When you press the Alt key you get a bar in firefox with the good old traditional menu. Here's a picture of how it looks now:

![Captura de pantalla de 2019-12-29 14-39-25](https://user-images.githubusercontent.com/14283056/71557055-4f526300-2a49-11ea-9398-675a0d0c6f28.png)

And here's an example of how it could look - using a mockup I had made of the file manager - too lazy to create on for firefox as well.

![Alt_focus_search](https://user-images.githubusercontent.com/14283056/71557082-cb4cab00-2a49-11ea-8ea8-fb528b161f11.png)

**Comment by Zonnev** [comment]
The Alt-key menu has same theme as bookmark bar, that's a reason why I will not theme it like a tab bar. I think only the tab bar should be different than the rest. But your request made me see a difference in the height of the Alt-key menu and the height of when you put the menu bar active. So I adjusted that in the latest userChrome.

**Comment by ChrisP4** [comment]
Thank you so very much! Not only did you notice the difference in height which I didn't mention, your answer combined with your latest commit was enough for me (I don't know how to code, don't know any css) to tweak it to my liking. 

<3

![Captura de pantalla de 2019-12-29 17-34-05](https://user-images.githubusercontent.com/14283056/71558991-93516200-2a61-11ea-9c9e-383c2c6170a0.png)
