### ISSUE TITLE
the description content of  tab and close button is not vertical align

### ISSUE THREAD

**Issue by Luancord** [Zonnev/elementaryos-firefox-theme#62]
![Captura de pantalla de 2020-02-19 13-11-25](https://user-images.githubusercontent.com/7141147/74866956-6448c580-5319-11ea-9712-7f4060cff4b6.png)

I recently installed because I saw it on videos and images but when I restarted firefox I noticed that the description content was not vertical align, currently I am on Hera and firefox on 73 version. My screen resolution is 1920*1080

**Comment by Zonnev** [comment]
You have "touch mode" enabled in customize panel. It should be on "normal mode".

**Comment by Zonnev** [comment]
In the latest userChrome I made "touch mode" back to normal, so you can use touch now without the content moving.

**Comment by Luancord** [comment]
Thank you! That works
