### ISSUE TITLE
Settings icon is squeezed in Firefox version (74.0)

### ISSUE THREAD

**Issue by TheLinuxEXP** [Zonnev/elementaryos-firefox-theme#64]
In Firefox 74.0, the settings icon is squeezed , as if it had less space to occupy than before:

![Screenshot from 2020-03-29 14-55-40](https://user-images.githubusercontent.com/54111876/77849638-74cc4580-71cd-11ea-8a58-7bc0d61105ec.png)

The icon was previously correctly sized

Running Firefox 74.0 (repository version), on elementary OS 5.1.2 on kernel 4.15.0-91-generic

**Comment by Zonnev** [comment]
Hello, maybe you use an old userChrome? I had this problem a few Firefox versions back and corrected it.

**Comment by TheLinuxEXP** [comment]
Hi! Thanks, I'll try that.

**Comment by Zonnev** [comment]
Be sure to use the latest userChrome. Hopefully the squeezed menu icon doesn't appear then.

**Comment by TheLinuxEXP** [comment]
I used the latest UserChrome, and it fixed the issue, thanks! I'm closing it.
