### ISSUE TITLE
[Question] I want the private mode as my default

### ISSUE THREAD

**Issue by bithons** [Zonnev/elementaryos-firefox-theme#66]
Hi,

First of all thank you for the (very) nice theme. I don't know if I am at the right section to ask a question but, my question is. Can I use the private mode's theme as my default theme? So yes, how can I do that?

Best regards,
Mert Somun

**Comment by Zonnev** [comment]
Hello, you can do this by editting firefox.desktop.

1. Right click on Files icon and choose 'new window as administrator'. Type in your password.
2. Go to Filesystem > usr > share > applications. Look for firefox.desktop.
3. Open firefox.desktop with Code.
4. On line 153 change the line to `Exec=firefox %u --private-window`

Now you have private mode as default.

**Comment by bithons** [comment]
> Hello, you can do this by editting firefox.desktop.
> 
>     1. Right click on Files icon and choose 'new window as administrator'. Type in your password.
> 
>     2. Go to Filesystem > usr > share > applications. Look for firefox.desktop.
> 
>     3. Open firefox.desktop with Code.
> 
>     4. On line 153 change the line to `Exec=firefox %u --private-window`
> 
> 
> Now you have private mode as default.

Thank you for your fast reply, but my actual question is how can I use the private window theme as my default. What you did write me is using private windows as default. Thank you for your time.

**Comment by Zonnev** [comment]
That a more difficult task to do but you can do it this way:

1. Open userChrome and delete line 7 to 574 (line 7 to 443 if you want to keep dark mode).
2. Then copy the whole private browsing section and paste it on line 7.
3. Remove `[privatebrowsingmode="temporary"]` behind all elements of the **pasted** css.

I think then you have private mode as default.

**Note:** If you want to use dark mode as well, then you need to keep `/* DARK MODE */` and `/* buttons in DARK MODE */` sections too.

Good luck!
