### ISSUE TITLE
Tabs are cut off when density is set to Touch in customizer

### ISSUE THREAD

**Issue by grandeljay** [Zonnev/elementaryos-firefox-theme#67]
Pretty much the title.

![image](https://user-images.githubusercontent.com/45571053/79488268-c40dd500-8019-11ea-9cb3-1d77210bc8b2.png)

I know CSS well, but I'm a long time Windows user, who just switched to Linux. I'd be willing to attempt making a PR with some guidance on how to make/preview changes to the CSS file in my browser.

EDIT: I found the css file and can edit it but I have to restart Firefox to see changes, is this the way of doing things? Is there a way to preview changes or inspect elements, at the moment I'm just guessing stuff.

**Comment by Zonnev** [comment]
The density modes like touch don't have CSS elements to adjust, so I can't do anything about that problem.

Restarting Firefox is what I do as well and I don't know another way to refresh the browser more quickly. You can change CSS in the Browser Toolbox, but that's only for preview, it's not for userChrome CSS editing.

**Comment by grandeljay** [comment]
I see, thanks.

I noticed a lot of `!important` statements in the code, are these all necessary? It seems they were placed to avoid/overwrite some conflict, is there a way to find out if firefox loads other css files which are overwriting rules from this file?

I'm hoping we can make the tabs more fluid so they scale nicely/responsively regardless of density set in the customizer. Can we achieve this by avoiding using px [entirely]?

So far I was able to play around with the tab size but their overflow seems to be hidden, I wasn't able to increase the parents size, do you know what I mean, could you point me int he right direction?

Thanks
Jay

**Comment by Zonnev** [comment]
I think with touch density we need to use a variable height for the tabs and the tabs toolbar. Now its set by px. Under section Tabs in the userChrome I begin with tab minimum height in px, this can be a variable too maybe. I havent played with it yet.

Do you have Browser toolbox enabled in web developer in Firefox? There you can see which elements have what CSS. For example you will see the tabs consist of different elements like a tab background and tab content. This is your friend when it comes to userChrome editing.

Edit: you found it already.

**Comment by Zonnev** [comment]
In the new userChrome I made touch density back to normal. I found the element for the tabs close button growing in touch mode and changed the padding back to zero.
