### ISSUE TITLE
Respect the CSD Button Layout

### ISSUE THREAD

**Issue by Fatih20** [Zonnev/elementaryos-firefox-theme#68]
I use elementaryOS. Through the gnome tweaks folder, I set my button layout as OS X instead of classic elementary. Is there a way for this theme to use the layout used by the user instead of the classic elementary?

**Comment by Zonnev** [comment]
This theme only uses elementary style button layout. It's because normally the buttons are in the tab bar right next to each other. I use CSS to set them apart, you need to write new CSS for other button layouts. OSX layout is quite easy to make, but other layouts like only close to left or right and the other button to the other side are impossible to write CSS for.

**Comment by Fatih20** [comment]
Is it possible to have multiple CSS to enable multiple button layout that the user then chose themselves to match their system button layout?

**Comment by Zonnev** [comment]
I could make multiple userChrome files and make a folder for each in my master. It's not possible to create buttons in Firefox so users can choose between different window button layouts.

I will think about creating an OSX and Windows button layout for this theme. I will post it here when it's ready.

**Comment by Fatih20** [comment]
Cool, thanks!

**Comment by Zonnev** [comment]
I have uploaded the userChrome files for OSX and Windows button layout in Tweaks. 

Here are the links:
[OSX style buttons](https://github.com/Zonnev/elementaryos-firefox-theme/tree/master/OSX%20button%20layout)
[Windows style buttons](https://github.com/Zonnev/elementaryos-firefox-theme/tree/master/Windows%20button%20layout)

**Comment by Fatih20** [comment]
I think you should reference the pull request you did here. Yes, it worked great, thanks!

**Comment by Cjnator38** [comment]
What about Minimize Left?

**Comment by Cjnator38** [comment]
![image](https://user-images.githubusercontent.com/39870226/79647779-f59bb300-8175-11ea-97df-d13ee83f447e.png)

**Comment by Zonnev** [comment]
@Cjnator38 I have made all button layout options and put the userChrome files in folders in my master.

**Comment by Cjnator38** [comment]
How do I apply the layouts?

**Comment by Zonnev** [comment]
@Cjnator38 

1. You need to download the master zip file
2. Go to your `chrome` folder in your `.mozilla/firefox/{your profile}` directory and overwrite the old `userChrome.css` with the `userChrome.css` from the `Minimise left` folder in the master.

**Comment by Zonnev** [comment]
At everyone, I changed the readme with an addition about installing the window buttons layout.
https://github.com/Zonnev/elementaryos-firefox-theme#install-a-window-control-button-layout

**Comment by Zonnev** [comment]
Hello, I made some mistakes with the button layouts. **When you show the bookmarks bar, the buttons go downward.** I'm working on it. At the same time I'm working on the dark mode that you can set active with just the Tweaks dark mode setting. No need for setting the dark mode in the customize panel. Be patient for things to come!

**Comment by Zonnev** [comment]
All is fixed, the buttons respect CSD layouts so I close this issue.
