### ISSUE TITLE
The height of the tab is just slightly too short.

### ISSUE THREAD

**Issue by Fatih20** [Zonnev/elementaryos-firefox-theme#70]
This might sound trivial but subtle things like this made a huge difference in terms of UI/UX. It also should match Epiphany's height, which IMHO, the perfect sweet spot.
![Screenshot from 2020-04-17 20 01 40](https://user-images.githubusercontent.com/51940383/79572079-86c34900-80e6-11ea-95ea-ce57b0435f0f.png)

**Comment by Zonnev** [comment]
Hmm, at my end the tab bar height is the same as Epiphany.
