### ISSUE TITLE
Dark mode support from Tweaks + window buttons are fixed

### ISSUE THREAD

**Issue by Zonnev** [Zonnev/elementaryos-firefox-theme#71]
The window buttons are now secured and fixed. The dark mode has now to be set in Tweaks to take effect. If you set dark mode in Firefox, the navigation and tab bar are not themed so you have to use Tweaks. If this is a problem for you, reply to me in this issue. Thank you for trying the theme out!

**Comment by jmbmkn** [comment]
This is a shame, I don't really want to install Elementary Tweaks, but I was previously using the dark mode with your theme. Do I have another option?

**Comment by Zonnev** [comment]
Sure its possible to have a dark mode without Tweaks, only the window buttons will be darker than the rest. I will look into it to restore the dark mode without Tweaks.

**Comment by Zonnev** [comment]
I have restored the dark mode, you can use it now. Be sure to use the latest userChrome.
