### ISSUE TITLE
Black pixels in window corner look out of place

### ISSUE THREAD

**Issue by Alterae** [Zonnev/elementaryos-firefox-theme#77]
![Screenshot from 2020-06-02 08 11 51@2x](https://user-images.githubusercontent.com/27498421/83530364-dc8e5d80-a4a8-11ea-9d3d-78667794d9e3.png)
This is a screenshot of the top left-hand corner of firefox with this theme applied.

![Screenshot from 2020-06-02 08 14 01@2x](https://user-images.githubusercontent.com/27498421/83530488-08114800-a4a9-11ea-84e0-77259a377687.png)
This is a screenshot of the same corner of a native elementaryOS window.

As you can see, there's a small but noticeable disparity.

**Comment by Zonnev** [comment]
Hello, you are right about this. This is showing a part of the main-window, which can't have a border radius or an opacity value or a rgba value. Yes, I can make it a colour, but all window borders have an opacity, so the greyish colour change with the background. I can't do anything to make it dissapear...

**Comment by Zonnev** [comment]
I'll make the background colour white, it makes the best result. I update all userChrome files soon.
