### ISSUE TITLE
Can't install in firefox flatpak version

### ISSUE THREAD

**Issue by Surendrajat** [Zonnev/elementaryos-firefox-theme#79]
Says... `Check Firefox installation ... failed, please check Firefox installation, unable to find /home/user/.mozilla/firefox` as I've installed firefox from flatpak.

**Comment by Zonnev** [comment]
You are right, the installer doesn't support the Firefox flatpak version. If you want to install the userChrome by hand, in the flatpak version of Firefox you can not open the profile folder so no userChrome can be added. 

If someone knows where to put the `chrome` folder on the flatpak version, I would be happy to know. 

For now, use the repo version of Firefox which installs in `.mozilla` folder.

**Comment by Surendrajat** [comment]
I got it now and will open a PR shortly.

**Comment by Akruidenberg** [comment]
> I got it now and will open a PR shortly.
> 
> However, the dir is: `~/.var/app/org.mozilla.firefox/.mozilla/firefox/`

Same issue here. Tried in a live session to copy the userchrome.css file to `/home/elementary/.var/app/org.mozilla.firefox/.mozilla/firefox/cweg7jhz.default-release/chrome`. After that i set `about:config` toolkit to `true`.  Nothing is working. 
However, the deb version is working fine. How did you get it working?

**Comment by Zonnev** [comment]
> > I got it now and will open a PR shortly.
> > However, the dir is: `~/.var/app/org.mozilla.firefox/.mozilla/firefox/`
> 
> Same issue here. Tried in a live session to copy the userchrome.css file to `/home/elementary/.var/app/org.mozilla.firefox/.mozilla/firefox/cweg7jhz.default-release/chrome`. After that i set `about:config` toolkit to `true`. Nothing is working.
> However, the deb version is working fine. How did you get it working?

Maybe you have more profile folders? Put the `chrome` folder in the profile folder with the most files.

**Comment by Zonnev** [comment]
@Surendrajat I have added an installation guide for Firefox flatpak version in the readme.

**Comment by Akruidenberg** [comment]
> @Surendrajat I have added an installation guide for Firefox flatpak version in the readme.

Did a fresh install of elementary with the new instructions in the readme. It dont work. The deb version is working fine.

What to do next?

**Comment by Surendrajat** [comment]
@Akruidenberg Try to install with the install script now. It should work.

**Comment by Akruidenberg** [comment]
> @Akruidenberg Try to install with the install script now. It should work.

Yes, its working fine now. The only problem i have now is that Firefox icon is double in my dock. The deb version dont have this problem.

**Comment by Surendrajat** [comment]
@Akruidenberg That is a known issue for flatpak version. I'm facing the same.

**Comment by Zonnev** [comment]
https://elementaryos.stackexchange.com/questions/18/one-of-my-apps-has-a-second-fuzzy-icon-in-plank-how-can-i-workaround-this 

This might help @Surendrajat @Akruidenberg

**Comment by Surendrajat** [comment]
Thanks @Zonnev it works.

For anyone else having same issue, I've added **`StartupWMClass=Navigator`** in `~/.local/share/flatpak/exports/share/applications/org.mozilla.firefox.desktop` file at the end of all three entries:
 (`Desktop Entry`, `Desktop Action new-window` & `Desktop Action new-private-window`)
