### ISSUE TITLE
Missing 'margin-right' for close button on tabs?

### ISSUE THREAD

**Issue by gre0j** [Zonnev/elementaryos-firefox-theme#82]
Is there a missing entry after line **435**? 
https://github.com/Zonnev/elementaryos-firefox-theme/blob/7acd897f8a6cc2dd60fa338cf82b642aedb48cfd/userChrome.css#L433-L439

Because at first use I noticed some misalignment with the close-buttons on the tabs…
![Without fix](https://user-images.githubusercontent.com/23266409/87089872-5b5c8000-c237-11ea-9733-698cdbb719b2.png)

…so I changed/added the following there…
```
  margin-left: -3px !important;
  margin-right: 3px !important;
```

…and now it looks ok for me but I just want to ask whether its correct or not what I did.
![Close Buttons](https://user-images.githubusercontent.com/23266409/87086448-e6d31280-c231-11ea-9f45-924c90d3f235.png)

**Comment by gre0j** [comment]
#83

**Comment by Zonnev** [comment]
Thank you. For touch density `margin-right` is indeed needed, but the value can be `0px`. I will change it myself.
