### ISSUE TITLE
Different control buttons in the history window

### ISSUE THREAD

**Issue by Khomyak-sibiryak** [Zonnev/elementaryos-firefox-theme#84]
Hello! I noticed that the control buttons in the history window are different. This is how the buttons look when you hover:
![Ekrankopita je 2020-07-12 18 11 54](https://user-images.githubusercontent.com/51476127/87244976-02583c00-c431-11ea-88fa-9eb984cb780e.png) ![Ekrankopita je 2020-07-12 18 12 38](https://user-images.githubusercontent.com/51476127/87244988-11d78500-c431-11ea-81af-42785b15fc9b.png)
And so when activated:
![Ekrankopita je 2020-07-12 18 13 16](https://user-images.githubusercontent.com/51476127/87245030-6c70e100-c431-11ea-8d39-fe493feaf288.png) ![Ekrankopita je 2020-07-12 18 13 42](https://user-images.githubusercontent.com/51476127/87245034-75fa4900-c431-11ea-9bd4-2711fc69670a.png)
Could you fix this? Thank.

**Comment by Zonnev** [comment]
Thank you. I fixed it in a way that the back button hover now is the same as forward button by removing the margins of the back button.

**Comment by Khomyak-sibiryak** [comment]
The buttons are now the same size, but the back button has a circle, can I remove it too?

**Comment by Zonnev** [comment]
You can not style this part of the browser without styling the default back button too. "Library" just uses the default back and forward buttons. The circle is meant to be this way as it matches the elementary OS style, so you better not remove it.

**Comment by Khomyak-sibiryak** [comment]
The forward button does not have such a circle.

**Comment by Zonnev** [comment]
> 
> 
> The forward button does not have such a circle.

I noticed that too but I can not style "Library", so I can not edit anything in that window.
