### ISSUE TITLE
back button always appears clickable when window is defocused

### ISSUE THREAD

**Issue by llama-from-heck** [Zonnev/elementaryos-firefox-theme#86]
i'm using firefox 81.0 on elementary os 5.1.7 hera. i just installed the theme today - it looks great! but when the window isn't selected, the back button always appears darker (as if i can click it) - even when it isn't actually clickable

![Screen record from 2020-09-28 15 59 46](https://user-images.githubusercontent.com/72047339/94486557-37109f80-01a5-11eb-8fbd-ef25fa805a48.gif)

**Comment by Zonnev** [comment]
As you can see, I fixed it. Thank you for addressing this issue!

**Comment by llama-from-heck** [comment]
oh, that was fast!! it's fixed for me now. thanks!
