### ISSUE TITLE
Closing tabs when there is multiple ones. Tabs should only resize when the mouse leaves the tab bar area.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#89]
1- Open multiple tabs until the tabs size starts to change.
2- Select one tab in middle and press the close (x) button.

**Result:** Unlike the default Firefox theme, tabs move beneath the mouse cursor when the close button is pressed which makes it difficult to close multiple tabs this way. This doesn't seem to happen on the default Firefox theme because the tab size doesn't change until the mouse leaves the tab bar area.

Is this something that can be fixed?

**Comment by Zonnev** [comment]
Hi, thank you for discovering this issue. I have deleted the tab width from the userChrome's in order to make this work again. I think in this case function goes over form and the tab width of the default Firefox isn't very much smaller than the default eOS tab width (few pixels larger).

**Comment by Blast-City** [comment]
Thank you very much for all the trouble.

It seems to be working great. Closing the last tab instead of a middle one shows the same problem, but this could be related to the close button being on the opposite side.

Thanks again and sorry for posting multiple issues in a short period of time.
