### ISSUE TITLE
Strange black rectangle on developer tools.

### ISSUE THREAD

**Issue by MauricioGlz** [Zonnev/elementaryos-firefox-theme#90]
When using this theme, the developer tools on detached mode it has a horrible black rectangle behind. Also this happens on any other popup window.

**Comment by Zonnev** [comment]
It's not my theme who does this. It's an elementary OS problem rendering title bars from Firefox. You can see it when you fresh up Firefox to its original state and enable title bar. 

Here is a fix:
https://www.reddit.com/r/elementaryos/comments/j3h3fp/firefox_users_anyone_seeing_an_issue_where/g7uhgmr?utm_source=share&utm_medium=web2x&context=3

**Comment by MauricioGlz** [comment]
Just tried but does not fix mine neither.  Well I think we can only wait.

**Comment by Zonnev** [comment]
I think they are working on it to figure it out. https://github.com/elementary/gala/issues/948

**Comment by Zbergen-cli** [comment]
For me, similar problems were solved by running `env GTK_CSD=0 firefox`.

**Comment by Zonnev** [comment]
@Zbergen-cli Thanks a million! 

@MauricioGlz You can adjust the `firefox.desktop` file in `/usr/share/applications`. Just open the file with Code and look for `Exec = firefox %u` and change it into `Exec=env GTK_CSD=0 firefox %u`.  Dont forget to log in Files as administrator.

**Comment by Zonnev** [comment]
I think to make the workaround more permanent and easier to adjust, is to install [AppEditor](https://appcenter.elementary.io/com.github.donadigo.appeditor/) and edit `firefox %u` with `env GTK_CSD=0 firefox %u`.

**Comment by Blast-City** [comment]
This seems to have been fixes some versions ago.

Can you confirm and close this issue? Thanks.

**Comment by Zonnev** [comment]
I can confirm this issue is not present anymore.
