### ISSUE TITLE
Space extension icons out more

### ISSUE THREAD

**Issue by BadCo-NZ** [Zonnev/elementaryos-firefox-theme#93]
Hi,

This is a great theme for ElementryOS, however in my crappy laptop screen with 1366x768 the extension icons are all crammed together and the number badges overlap other icons.

Can they have their spacing increased?

![Screenshot from 2020-10-31 19 15 28](https://user-images.githubusercontent.com/50016048/97772602-8afc1300-1bad-11eb-9a0d-9d971efbda32.png)

Thanks!

**Comment by Zonnev** [comment]
I have added padding to the extension badges so the spacing between them is increased. Use the latest userChrome!

**Comment by BadCo-NZ** [comment]
It's perfect! I should have done this ages ago 

> I have added padding to the extension icons so the spacing between them is increased. Use the latest userChrome!

Nailed it! I should have mentioned this ages ago :smile: 

![Screenshot from 2020-11-01 09 11 49](https://user-images.githubusercontent.com/50016048/97789081-8a677a80-1bb5-11eb-85b9-6dc29995d132.png)
