### ISSUE TITLE
eOS 6.0 testers: you can install the Odin version of the theme!

### ISSUE THREAD

**Issue by Zonnev** [Zonnev/elementaryos-firefox-theme#94]
You can find it here:
https://github.com/Zonnev/elementaryos-firefox-theme/tree/elementaryos-odin-firefox-theme

**Comment by jonseppanen** [comment]
I have installed this on latest eos nightly. Getting a strange black border around the window though - any way to fix that?

**Comment by Zonnev** [comment]
@jonseppanen All I know is that Firefox Nightly is acting strange in eOS Hera. It has a double transparent border there. I haven't installed Nightly on Odin so I can not check it but I'm sure it's a Firefox bug and I'm unable to fix that.

In the eOS Odin theme I removed my own made window border because now Odin draws that border, but I guess this isn't the problem...

**Comment by mr-islam** [comment]
I just noticed there's an Odin version of this theme and installed it yesterday — it looks stunning! Amazing work 😍
