### ISSUE TITLE
Privacy Mode > Icons for | Sidebar | PrivayMode | Bookmarks | are black instead of white when placed in Tabbar

### ISSUE THREAD

**Issue by gre0j** [Zonnev/elementaryos-firefox-theme#99]
Is it possible to make these three icons white instead of black when they are placed on the TabBar? 
Now I also noticed in this screenshot, the text for the 'zoom-function' is black 🙈️

![Bildschirmfoto von 2020-12-26 16-49-34](https://user-images.githubusercontent.com/23266409/103155137-186a7680-479d-11eb-9403-b2b571153c95.png)

Thanks for your work 😊️

**Comment by Zonnev** [comment]
I have made the icons white in the new userChrome's. You can now install it. The zoom-function I will look at later.

**Comment by Zonnev** [comment]
In the newest userChrome's the zoom-function is made white too for Private mode. You can install it now and thank you for showing me the issues!

**Comment by gre0j** [comment]
Awesome! Thank you 😎️
